/* libInventoryCount.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __LIBINVENTORYCOUNT_H__
#define __LIBINVENTORYCOUNT_H__

#include <glib.h>
#include <glib-object.h>
#include <SinticBolivia.h>
#include <gee.h>
#include <GtkSinticBolivia.h>
#include <gtk/gtk.h>
#include <gmodule.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define EPOS_TYPE_HELPER_INVENTORY_COUNT (epos_helper_inventory_count_get_type ())
#define EPOS_HELPER_INVENTORY_COUNT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_HELPER_INVENTORY_COUNT, EPosHelperInventoryCount))
#define EPOS_HELPER_INVENTORY_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_HELPER_INVENTORY_COUNT, EPosHelperInventoryCountClass))
#define EPOS_IS_HELPER_INVENTORY_COUNT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_HELPER_INVENTORY_COUNT))
#define EPOS_IS_HELPER_INVENTORY_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_HELPER_INVENTORY_COUNT))
#define EPOS_HELPER_INVENTORY_COUNT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_HELPER_INVENTORY_COUNT, EPosHelperInventoryCountClass))

typedef struct _EPosHelperInventoryCount EPosHelperInventoryCount;
typedef struct _EPosHelperInventoryCountClass EPosHelperInventoryCountClass;
typedef struct _EPosHelperInventoryCountPrivate EPosHelperInventoryCountPrivate;

#define EPOS_TYPE_SB_MODULEINVENTORYCOUNT (epos_sb_moduleinventorycount_get_type ())
#define EPOS_SB_MODULEINVENTORYCOUNT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_SB_MODULEINVENTORYCOUNT, EPosSB_ModuleInventoryCount))
#define EPOS_SB_MODULEINVENTORYCOUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_SB_MODULEINVENTORYCOUNT, EPosSB_ModuleInventoryCountClass))
#define EPOS_IS_SB_MODULEINVENTORYCOUNT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_SB_MODULEINVENTORYCOUNT))
#define EPOS_IS_SB_MODULEINVENTORYCOUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_SB_MODULEINVENTORYCOUNT))
#define EPOS_SB_MODULEINVENTORYCOUNT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_SB_MODULEINVENTORYCOUNT, EPosSB_ModuleInventoryCountClass))

typedef struct _EPosSB_ModuleInventoryCount EPosSB_ModuleInventoryCount;
typedef struct _EPosSB_ModuleInventoryCountClass EPosSB_ModuleInventoryCountClass;
typedef struct _EPosSB_ModuleInventoryCountPrivate EPosSB_ModuleInventoryCountPrivate;

#define EPOS_TYPE_WIDGET_COMPARE_WORKSHEETS (epos_widget_compare_worksheets_get_type ())
#define EPOS_WIDGET_COMPARE_WORKSHEETS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_COMPARE_WORKSHEETS, EPosWidgetCompareWorksheets))
#define EPOS_WIDGET_COMPARE_WORKSHEETS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_COMPARE_WORKSHEETS, EPosWidgetCompareWorksheetsClass))
#define EPOS_IS_WIDGET_COMPARE_WORKSHEETS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_COMPARE_WORKSHEETS))
#define EPOS_IS_WIDGET_COMPARE_WORKSHEETS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_COMPARE_WORKSHEETS))
#define EPOS_WIDGET_COMPARE_WORKSHEETS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_COMPARE_WORKSHEETS, EPosWidgetCompareWorksheetsClass))

typedef struct _EPosWidgetCompareWorksheets EPosWidgetCompareWorksheets;
typedef struct _EPosWidgetCompareWorksheetsClass EPosWidgetCompareWorksheetsClass;
typedef struct _EPosWidgetCompareWorksheetsPrivate EPosWidgetCompareWorksheetsPrivate;

#define EPOS_TYPE_WIDGET_WORKSHEET (epos_widget_worksheet_get_type ())
#define EPOS_WIDGET_WORKSHEET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_WORKSHEET, EPosWidgetWorksheet))
#define EPOS_WIDGET_WORKSHEET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_WORKSHEET, EPosWidgetWorksheetClass))
#define EPOS_IS_WIDGET_WORKSHEET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_WORKSHEET))
#define EPOS_IS_WIDGET_WORKSHEET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_WORKSHEET))
#define EPOS_WIDGET_WORKSHEET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_WORKSHEET, EPosWidgetWorksheetClass))

typedef struct _EPosWidgetWorksheet EPosWidgetWorksheet;
typedef struct _EPosWidgetWorksheetClass EPosWidgetWorksheetClass;

#define EPOS_WIDGET_COMPARE_WORKSHEETS_TYPE_COLUMNS (epos_widget_compare_worksheets_columns_get_type ())

#define EPOS_TYPE_WIDGET_INVENTORY_COUNT (epos_widget_inventory_count_get_type ())
#define EPOS_WIDGET_INVENTORY_COUNT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_INVENTORY_COUNT, EPosWidgetInventoryCount))
#define EPOS_WIDGET_INVENTORY_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_INVENTORY_COUNT, EPosWidgetInventoryCountClass))
#define EPOS_IS_WIDGET_INVENTORY_COUNT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_INVENTORY_COUNT))
#define EPOS_IS_WIDGET_INVENTORY_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_INVENTORY_COUNT))
#define EPOS_WIDGET_INVENTORY_COUNT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_INVENTORY_COUNT, EPosWidgetInventoryCountClass))

typedef struct _EPosWidgetInventoryCount EPosWidgetInventoryCount;
typedef struct _EPosWidgetInventoryCountClass EPosWidgetInventoryCountClass;
typedef struct _EPosWidgetInventoryCountPrivate EPosWidgetInventoryCountPrivate;

#define EPOS_WIDGET_INVENTORY_COUNT_TYPE_COLUMNS (epos_widget_inventory_count_columns_get_type ())

#define EPOS_TYPE_WIDGET_NEW_INVENTORY_COUNT (epos_widget_new_inventory_count_get_type ())
#define EPOS_WIDGET_NEW_INVENTORY_COUNT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_NEW_INVENTORY_COUNT, EPosWidgetNewInventoryCount))
#define EPOS_WIDGET_NEW_INVENTORY_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_NEW_INVENTORY_COUNT, EPosWidgetNewInventoryCountClass))
#define EPOS_IS_WIDGET_NEW_INVENTORY_COUNT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_NEW_INVENTORY_COUNT))
#define EPOS_IS_WIDGET_NEW_INVENTORY_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_NEW_INVENTORY_COUNT))
#define EPOS_WIDGET_NEW_INVENTORY_COUNT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_NEW_INVENTORY_COUNT, EPosWidgetNewInventoryCountClass))

typedef struct _EPosWidgetNewInventoryCount EPosWidgetNewInventoryCount;
typedef struct _EPosWidgetNewInventoryCountClass EPosWidgetNewInventoryCountClass;
typedef struct _EPosWidgetNewInventoryCountPrivate EPosWidgetNewInventoryCountPrivate;

#define EPOS_WIDGET_NEW_INVENTORY_COUNT_TYPE_COLUMNS (epos_widget_new_inventory_count_columns_get_type ())
typedef struct _EPosWidgetWorksheetPrivate EPosWidgetWorksheetPrivate;

#define EPOS_WIDGET_WORKSHEET_TYPE_COLUMNS (epos_widget_worksheet_columns_get_type ())

#define EPOS_TYPE_DIALOG_WORKSHEET_SELECTOR (epos_dialog_worksheet_selector_get_type ())
#define EPOS_DIALOG_WORKSHEET_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_DIALOG_WORKSHEET_SELECTOR, EPosDialogWorksheetSelector))
#define EPOS_DIALOG_WORKSHEET_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_DIALOG_WORKSHEET_SELECTOR, EPosDialogWorksheetSelectorClass))
#define EPOS_IS_DIALOG_WORKSHEET_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_DIALOG_WORKSHEET_SELECTOR))
#define EPOS_IS_DIALOG_WORKSHEET_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_DIALOG_WORKSHEET_SELECTOR))
#define EPOS_DIALOG_WORKSHEET_SELECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_DIALOG_WORKSHEET_SELECTOR, EPosDialogWorksheetSelectorClass))

typedef struct _EPosDialogWorksheetSelector EPosDialogWorksheetSelector;
typedef struct _EPosDialogWorksheetSelectorClass EPosDialogWorksheetSelectorClass;
typedef struct _EPosDialogWorksheetSelectorPrivate EPosDialogWorksheetSelectorPrivate;

struct _EPosHelperInventoryCount {
	GObject parent_instance;
	EPosHelperInventoryCountPrivate * priv;
};

struct _EPosHelperInventoryCountClass {
	GObjectClass parent_class;
};

struct _EPosSB_ModuleInventoryCount {
	SinticBoliviaGtkSBGtkModule parent_instance;
	EPosSB_ModuleInventoryCountPrivate * priv;
};

struct _EPosSB_ModuleInventoryCountClass {
	SinticBoliviaGtkSBGtkModuleClass parent_class;
};

struct _EPosWidgetCompareWorksheets {
	GtkBox parent_instance;
	EPosWidgetCompareWorksheetsPrivate * priv;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkNotebook* notebook;
	GtkBox* boxResults;
	GtkTreeView* treeviewResults;
	GtkButton* buttonPrintResults;
	GtkButtonBox* buttonbox1;
	GtkButton* buttonClose;
	GdkPixbuf* pixbufCheck;
	GdkPixbuf* pixbufCross;
	GeeArrayList* worksheets;
};

struct _EPosWidgetCompareWorksheetsClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_COUNT,
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_ID,
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_CODE,
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_NAME,
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_PASS,
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_UNITS,
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_CASES,
	EPOS_WIDGET_COMPARE_WORKSHEETS_COLUMNS_N_COLS
} EPosWidgetCompareWorksheetsColumns;

struct _EPosWidgetInventoryCount {
	GtkBox parent_instance;
	EPosWidgetInventoryCountPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkImage* image1;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkButton* buttonPrint;
	GtkButton* buttonSubmitWorkSheet;
	GtkButton* buttonEditWorksheet;
	GtkButton* buttonCompareWorksheets;
	GtkComboBox* comboboxStore;
	GtkTreeView* treeviewCounts;
	gint selectedCountId;
};

struct _EPosWidgetInventoryCountClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_INVENTORY_COUNT_COLUMNS_COUNT,
	EPOS_WIDGET_INVENTORY_COUNT_COLUMNS_ID,
	EPOS_WIDGET_INVENTORY_COUNT_COLUMNS_DESCRIPTION,
	EPOS_WIDGET_INVENTORY_COUNT_COLUMNS_TOTAL_PRODUCTS,
	EPOS_WIDGET_INVENTORY_COUNT_COLUMNS_STATUS,
	EPOS_WIDGET_INVENTORY_COUNT_COLUMNS_CREATION_DATE,
	EPOS_WIDGET_INVENTORY_COUNT_COLUMNS_N_COLS
} EPosWidgetInventoryCountColumns;

struct _EPosWidgetNewInventoryCount {
	GtkBox parent_instance;
	EPosWidgetNewInventoryCountPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkImage* image1;
	GtkComboBox* comboboxStore;
	GtkEntry* entryDescription;
	GtkEntry* entrySearchProduct;
	GtkComboBox* comboboxSearchBy;
	GtkButton* buttonAdd;
	GtkTreeView* treeviewProducts;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
};

struct _EPosWidgetNewInventoryCountClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_NEW_INVENTORY_COUNT_COLUMNS_COUNT,
	EPOS_WIDGET_NEW_INVENTORY_COUNT_COLUMNS_ID,
	EPOS_WIDGET_NEW_INVENTORY_COUNT_COLUMNS_CODE,
	EPOS_WIDGET_NEW_INVENTORY_COUNT_COLUMNS_PRODUCT,
	EPOS_WIDGET_NEW_INVENTORY_COUNT_COLUMNS_REMOVE,
	EPOS_WIDGET_NEW_INVENTORY_COUNT_COLUMNS_N_COLS
} EPosWidgetNewInventoryCountColumns;

struct _EPosWidgetWorksheet {
	GtkBox parent_instance;
	EPosWidgetWorksheetPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkLabel* labelStore;
	GtkLabel* labelCountDate;
	GtkLabel* labelDescription;
	GtkTreeView* treeviewProducts;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint countId;
	gint workSheet;
	gboolean update;
};

struct _EPosWidgetWorksheetClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_WORKSHEET_COLUMNS_COUNT,
	EPOS_WIDGET_WORKSHEET_COLUMNS_ID,
	EPOS_WIDGET_WORKSHEET_COLUMNS_CODE,
	EPOS_WIDGET_WORKSHEET_COLUMNS_NAME,
	EPOS_WIDGET_WORKSHEET_COLUMNS_UNITS,
	EPOS_WIDGET_WORKSHEET_COLUMNS_CASES,
	EPOS_WIDGET_WORKSHEET_COLUMNS_RESULT_ID,
	EPOS_WIDGET_WORKSHEET_COLUMNS_N_COLS
} EPosWidgetWorksheetColumns;

struct _EPosDialogWorksheetSelector {
	GtkDialog parent_instance;
	EPosDialogWorksheetSelectorPrivate * priv;
	GtkLabel* labelTitle;
	GtkScrolledWindow* scrolledwindow1;
	GtkTreeView* treeviewWorksheets;
	GtkButton* buttonCancel;
	GtkButton* buttonSelect;
	gint countId;
};

struct _EPosDialogWorksheetSelectorClass {
	GtkDialogClass parent_class;
};


GType epos_helper_inventory_count_get_type (void) G_GNUC_CONST;
GeeArrayList* epos_helper_inventory_count_GetWorksheet (gint count_id, gint result_number, SinticBoliviaDatabaseSBDatabase* _dbh);
GeeArrayList* epos_helper_inventory_count_GetCountProducts (gint count_id, SinticBoliviaDatabaseSBDatabase* _dbh);
EPosHelperInventoryCount* epos_helper_inventory_count_new (void);
EPosHelperInventoryCount* epos_helper_inventory_count_construct (GType object_type);
GType epos_sb_moduleinventorycount_get_type (void) G_GNUC_CONST;
void epos_sb_moduleinventorycount_AddHooks (EPosSB_ModuleInventoryCount* self);
void epos_sb_moduleinventorycount_hook_menu_item_inventory (EPosSB_ModuleInventoryCount* self, SinticBoliviaSBModuleArgs* args);
EPosSB_ModuleInventoryCount* epos_sb_moduleinventorycount_new (void);
EPosSB_ModuleInventoryCount* epos_sb_moduleinventorycount_construct (GType object_type);
GType sb_get_module_libinventorycount_type (GModule* inventory_count_module);
GType epos_widget_compare_worksheets_get_type (void) G_GNUC_CONST;
GType epos_widget_worksheet_get_type (void) G_GNUC_CONST;
GType epos_widget_compare_worksheets_columns_get_type (void) G_GNUC_CONST;
EPosWidgetCompareWorksheets* epos_widget_compare_worksheets_new (void);
EPosWidgetCompareWorksheets* epos_widget_compare_worksheets_construct (GType object_type);
void epos_widget_compare_worksheets_Build (EPosWidgetCompareWorksheets* self);
void epos_widget_compare_worksheets_SetEvents (EPosWidgetCompareWorksheets* self);
void epos_widget_compare_worksheets_OnButtonCloseClicked (EPosWidgetCompareWorksheets* self);
void epos_widget_compare_worksheets_OnButtonPrintResultsClicked (EPosWidgetCompareWorksheets* self);
void epos_widget_compare_worksheets_AppendWorksheet (EPosWidgetCompareWorksheets* self, gint count_id, gint result_number);
void epos_widget_compare_worksheets_CalculateResults (EPosWidgetCompareWorksheets* self);
GType epos_widget_inventory_count_get_type (void) G_GNUC_CONST;
GType epos_widget_inventory_count_columns_get_type (void) G_GNUC_CONST;
EPosWidgetInventoryCount* epos_widget_inventory_count_new (void);
EPosWidgetInventoryCount* epos_widget_inventory_count_construct (GType object_type);
void epos_widget_inventory_count_Build (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_SetEvents (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_OnButtonNewClicked (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_OnButtonPrintClicked (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_OnButtonSubmitWorkSheetClicked (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_OnButtonEditWorksheetClicked (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_OnButtonCompareWorksheetsClicked (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_OnWorksheetsSelected (EPosWidgetInventoryCount* self, gint count_id, gint* results, int results_length1);
void epos_widget_inventory_count_OnWorksheetsCompareSelected (EPosWidgetInventoryCount* self, gint count_id, gint* results, int results_length1);
void epos_widget_inventory_count_OnComboBoxStoreChanged (EPosWidgetInventoryCount* self);
void epos_widget_inventory_count_Refresh (EPosWidgetInventoryCount* self, gint store_id);
GType epos_widget_new_inventory_count_get_type (void) G_GNUC_CONST;
GType epos_widget_new_inventory_count_columns_get_type (void) G_GNUC_CONST;
EPosWidgetNewInventoryCount* epos_widget_new_inventory_count_new (void);
EPosWidgetNewInventoryCount* epos_widget_new_inventory_count_construct (GType object_type);
void epos_widget_new_inventory_count_Build (EPosWidgetNewInventoryCount* self);
void epos_widget_new_inventory_count_SetEvents (EPosWidgetNewInventoryCount* self);
void epos_widget_new_inventory_count_OnEntrySearchProductIconRelease (EPosWidgetNewInventoryCount* self, GtkEntryIconPosition icon, GdkEvent* e);
gboolean epos_widget_new_inventory_count_OnTreeViewProductsButtonReleaseEvent (EPosWidgetNewInventoryCount* self, GdkEventButton* args);
void epos_widget_new_inventory_count_OnButtonCancelClicked (EPosWidgetNewInventoryCount* self);
void epos_widget_new_inventory_count_OnButtonSaveClicked (EPosWidgetNewInventoryCount* self);
GType epos_widget_worksheet_columns_get_type (void) G_GNUC_CONST;
EPosWidgetWorksheet* epos_widget_worksheet_new (void);
EPosWidgetWorksheet* epos_widget_worksheet_construct (GType object_type);
void epos_widget_worksheet_Build (EPosWidgetWorksheet* self);
void epos_widget_worksheet_SetEvents (EPosWidgetWorksheet* self);
void epos_widget_worksheet_FillProducts (EPosWidgetWorksheet* self, gint count_id);
void epos_widget_worksheet_SetWorksheet (EPosWidgetWorksheet* self, gint count_id, gint worksheet);
void epos_widget_worksheet_OnCellUnitsEdited (EPosWidgetWorksheet* self, const gchar* path, const gchar* text);
void epos_widget_worksheet_OnCellCasesEdited (EPosWidgetWorksheet* self, const gchar* path, const gchar* text);
void epos_widget_worksheet_OnButtonCancelClicked (EPosWidgetWorksheet* self);
void epos_widget_worksheet_OnButtonSaveClicked (EPosWidgetWorksheet* self);
void epos_widget_worksheet_set_ShowButtons (EPosWidgetWorksheet* self, gboolean value);
void epos_widget_worksheet_set_Editable (EPosWidgetWorksheet* self, gboolean value);
GtkListStore* epos_widget_worksheet_get_Model (EPosWidgetWorksheet* self);
GType epos_dialog_worksheet_selector_get_type (void) G_GNUC_CONST;
EPosDialogWorksheetSelector* epos_dialog_worksheet_selector_new (gint count_id);
EPosDialogWorksheetSelector* epos_dialog_worksheet_selector_construct (GType object_type, gint count_id);
void epos_dialog_worksheet_selector_Build (EPosDialogWorksheetSelector* self);
void epos_dialog_worksheet_selector_SetEvents (EPosDialogWorksheetSelector* self);
void epos_dialog_worksheet_selector_Fill (EPosDialogWorksheetSelector* self);
void epos_dialog_worksheet_selector_OnButtonCancelClicked (EPosDialogWorksheetSelector* self);
void epos_dialog_worksheet_selector_OnButtonSelectClicked (EPosDialogWorksheetSelector* self);
gboolean epos_dialog_worksheet_selector_get_MultipleSelection (EPosDialogWorksheetSelector* self);
void epos_dialog_worksheet_selector_set_MultipleSelection (EPosDialogWorksheetSelector* self, gboolean value);


G_END_DECLS

#endif
