/* Chimuela.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __CHIMUELA_H__
#define __CHIMUELA_H__

#include <glib.h>
#include <GtkSinticBolivia.h>
#include <SinticBolivia.h>
#include <stdlib.h>
#include <string.h>
#include <gmodule.h>

G_BEGIN_DECLS


#define EPOS_TYPE_SB_MODULECHIMUELA (epos_sb_modulechimuela_get_type ())
#define EPOS_SB_MODULECHIMUELA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_SB_MODULECHIMUELA, EPosSB_ModuleChimuela))
#define EPOS_SB_MODULECHIMUELA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_SB_MODULECHIMUELA, EPosSB_ModuleChimuelaClass))
#define EPOS_IS_SB_MODULECHIMUELA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_SB_MODULECHIMUELA))
#define EPOS_IS_SB_MODULECHIMUELA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_SB_MODULECHIMUELA))
#define EPOS_SB_MODULECHIMUELA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_SB_MODULECHIMUELA, EPosSB_ModuleChimuelaClass))

typedef struct _EPosSB_ModuleChimuela EPosSB_ModuleChimuela;
typedef struct _EPosSB_ModuleChimuelaClass EPosSB_ModuleChimuelaClass;
typedef struct _EPosSB_ModuleChimuelaPrivate EPosSB_ModuleChimuelaPrivate;

struct _EPosSB_ModuleChimuela {
	SinticBoliviaGtkSBGtkModule parent_instance;
	EPosSB_ModuleChimuelaPrivate * priv;
	GPid chimuelaPid;
};

struct _EPosSB_ModuleChimuelaClass {
	SinticBoliviaGtkSBGtkModuleClass parent_class;
};


GType epos_sb_modulechimuela_get_type (void) G_GNUC_CONST;
void epos_sb_modulechimuela_hook_on_quit (EPosSB_ModuleChimuela* self, SinticBoliviaSBModuleArgs* args);
EPosSB_ModuleChimuela* epos_sb_modulechimuela_new (void);
EPosSB_ModuleChimuela* epos_sb_modulechimuela_construct (GType object_type);
GType sb_get_module_libchimuela_type (GModule* module);


G_END_DECLS

#endif
