/* Chimuela.vapi generated by valac.exe 0.24.0, do not modify. */

namespace EPos {
	[CCode (cheader_filename = "Chimuela.h")]
	public class SB_ModuleChimuela : SinticBolivia.Gtk.SBGtkModule, SinticBolivia.ISBModule {
		protected GLib.Pid chimuelaPid;
		public SB_ModuleChimuela ();
		protected void hook_on_quit (SinticBolivia.SBModuleArgs<string> args);
	}
}
[CCode (cheader_filename = "Chimuela.h")]
public static GLib.Type sb_get_module_libchimuela_type (GLib.Module module);
