/* Restaurant.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __RESTAURANT_H__
#define __RESTAURANT_H__

#include <glib.h>
#include <GtkSinticBolivia.h>
#include <SinticBolivia.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <gmodule.h>
#include <glib-object.h>

G_BEGIN_DECLS


#define WOOCOMMERCE_TYPE_SB_MODULERESTAURANT (woocommerce_sb_modulerestaurant_get_type ())
#define WOOCOMMERCE_SB_MODULERESTAURANT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_SB_MODULERESTAURANT, WoocommerceSB_ModuleRestaurant))
#define WOOCOMMERCE_SB_MODULERESTAURANT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_SB_MODULERESTAURANT, WoocommerceSB_ModuleRestaurantClass))
#define WOOCOMMERCE_IS_SB_MODULERESTAURANT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_SB_MODULERESTAURANT))
#define WOOCOMMERCE_IS_SB_MODULERESTAURANT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_SB_MODULERESTAURANT))
#define WOOCOMMERCE_SB_MODULERESTAURANT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_SB_MODULERESTAURANT, WoocommerceSB_ModuleRestaurantClass))

typedef struct _WoocommerceSB_ModuleRestaurant WoocommerceSB_ModuleRestaurant;
typedef struct _WoocommerceSB_ModuleRestaurantClass WoocommerceSB_ModuleRestaurantClass;
typedef struct _WoocommerceSB_ModuleRestaurantPrivate WoocommerceSB_ModuleRestaurantPrivate;

#define WOOCOMMERCE_TYPE_WIDGET_ENVIRONMENTS (woocommerce_widget_environments_get_type ())
#define WOOCOMMERCE_WIDGET_ENVIRONMENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_WIDGET_ENVIRONMENTS, WoocommerceWidgetEnvironments))
#define WOOCOMMERCE_WIDGET_ENVIRONMENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_WIDGET_ENVIRONMENTS, WoocommerceWidgetEnvironmentsClass))
#define WOOCOMMERCE_IS_WIDGET_ENVIRONMENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_WIDGET_ENVIRONMENTS))
#define WOOCOMMERCE_IS_WIDGET_ENVIRONMENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_WIDGET_ENVIRONMENTS))
#define WOOCOMMERCE_WIDGET_ENVIRONMENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_WIDGET_ENVIRONMENTS, WoocommerceWidgetEnvironmentsClass))

typedef struct _WoocommerceWidgetEnvironments WoocommerceWidgetEnvironments;
typedef struct _WoocommerceWidgetEnvironmentsClass WoocommerceWidgetEnvironmentsClass;
typedef struct _WoocommerceWidgetEnvironmentsPrivate WoocommerceWidgetEnvironmentsPrivate;

#define WOOCOMMERCE_TYPE_RESTAURANT_HELPER (woocommerce_restaurant_helper_get_type ())
#define WOOCOMMERCE_RESTAURANT_HELPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_RESTAURANT_HELPER, WoocommerceRestaurantHelper))
#define WOOCOMMERCE_RESTAURANT_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_RESTAURANT_HELPER, WoocommerceRestaurantHelperClass))
#define WOOCOMMERCE_IS_RESTAURANT_HELPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_RESTAURANT_HELPER))
#define WOOCOMMERCE_IS_RESTAURANT_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_RESTAURANT_HELPER))
#define WOOCOMMERCE_RESTAURANT_HELPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_RESTAURANT_HELPER, WoocommerceRestaurantHelperClass))

typedef struct _WoocommerceRestaurantHelper WoocommerceRestaurantHelper;
typedef struct _WoocommerceRestaurantHelperClass WoocommerceRestaurantHelperClass;
typedef struct _WoocommerceRestaurantHelperPrivate WoocommerceRestaurantHelperPrivate;

#define WOOCOMMERCE_TYPE_WIDGET_RESTAUTANT_OPTIONS (woocommerce_widget_restautant_options_get_type ())
#define WOOCOMMERCE_WIDGET_RESTAUTANT_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_WIDGET_RESTAUTANT_OPTIONS, WoocommerceWidgetRestautantOptions))
#define WOOCOMMERCE_WIDGET_RESTAUTANT_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_WIDGET_RESTAUTANT_OPTIONS, WoocommerceWidgetRestautantOptionsClass))
#define WOOCOMMERCE_IS_WIDGET_RESTAUTANT_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_WIDGET_RESTAUTANT_OPTIONS))
#define WOOCOMMERCE_IS_WIDGET_RESTAUTANT_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_WIDGET_RESTAUTANT_OPTIONS))
#define WOOCOMMERCE_WIDGET_RESTAUTANT_OPTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_WIDGET_RESTAUTANT_OPTIONS, WoocommerceWidgetRestautantOptionsClass))

typedef struct _WoocommerceWidgetRestautantOptions WoocommerceWidgetRestautantOptions;
typedef struct _WoocommerceWidgetRestautantOptionsClass WoocommerceWidgetRestautantOptionsClass;
typedef struct _WoocommerceWidgetRestautantOptionsPrivate WoocommerceWidgetRestautantOptionsPrivate;

struct _WoocommerceSB_ModuleRestaurant {
	SinticBoliviaGtkSBGtkModule parent_instance;
	WoocommerceSB_ModuleRestaurantPrivate * priv;
	gchar* resourceFile;
	gchar* resourceNs;
};

struct _WoocommerceSB_ModuleRestaurantClass {
	SinticBoliviaGtkSBGtkModuleClass parent_class;
};

struct _WoocommerceWidgetEnvironments {
	GtkBox parent_instance;
	WoocommerceWidgetEnvironmentsPrivate * priv;
	GtkWindow* windowRestaurant;
	GtkBox* boxRestaurant;
	GtkImage* image1;
	GtkTreeView* treeviewEnvironments;
	GtkImage* imageEnvironment;
	GtkButton* buttonEnvImage;
	GtkButton* buttonNewEnv;
	GtkButton* buttonDeleteEnv;
	GtkTreeView* treeviewTables;
	GtkImage* imageTable;
	GtkButton* buttonTableImage;
	GtkButton* buttonNewTable;
	GtkButton* buttonDeleteTable;
	gint current_env_id;
};

struct _WoocommerceWidgetEnvironmentsClass {
	GtkBoxClass parent_class;
};

struct _WoocommerceRestaurantHelper {
	GObject parent_instance;
	WoocommerceRestaurantHelperPrivate * priv;
};

struct _WoocommerceRestaurantHelperClass {
	GObjectClass parent_class;
};

struct _WoocommerceWidgetRestautantOptions {
	GtkBox parent_instance;
	WoocommerceWidgetRestautantOptionsPrivate * priv;
	GtkBuilder* ui;
	GtkWindow* windowOptions;
	GtkBox* boxOptions;
	GtkTreeView* treeviewOptions;
};

struct _WoocommerceWidgetRestautantOptionsClass {
	GtkBoxClass parent_class;
};


GType woocommerce_sb_modulerestaurant_get_type (void) G_GNUC_CONST;
extern GResource* woocommerce_sb_modulerestaurant_res_data;
extern GtkBuilder* woocommerce_sb_modulerestaurant_ui_restaurant;
GtkBuilder* woocommerce_sb_modulerestaurant_GetGladeUi (const gchar* ui_file);
void woocommerce_sb_modulerestaurant_init_menu_management (SinticBoliviaSBModuleArgs* args);
void woocommerce_sb_modulerestaurant_hook_init_sidebar (SinticBoliviaSBModuleArgs* args);
void woocommerce_sb_modulerestaurant_hook_inventory_tabs (SinticBoliviaSBModuleArgs* args);
WoocommerceSB_ModuleRestaurant* woocommerce_sb_modulerestaurant_new (void);
WoocommerceSB_ModuleRestaurant* woocommerce_sb_modulerestaurant_construct (GType object_type);
GType sb_get_module_type (GModule* restaurant_module);
GType woocommerce_widget_environments_get_type (void) G_GNUC_CONST;
extern gint woocommerce_widget_environments_instances;
WoocommerceWidgetEnvironments* woocommerce_widget_environments_new (void);
WoocommerceWidgetEnvironments* woocommerce_widget_environments_construct (GType object_type);
void woocommerce_widget_environments_Build (WoocommerceWidgetEnvironments* self);
void woocommerce_widget_environments_SetEvents (WoocommerceWidgetEnvironments* self);
void woocommerce_widget_environments_RefreshEnvironments (WoocommerceWidgetEnvironments* self);
void woocommerce_widget_environments_RefreshTables (WoocommerceWidgetEnvironments* self, gint env_id);
void woocommerce_widget_environments_OnButtonNewEnvClicked (WoocommerceWidgetEnvironments* self);
void woocommerce_widget_environments_OnButtonDeleteEnvClicked (WoocommerceWidgetEnvironments* self);
void woocommerce_widget_environments_OnEnvironmenNameEdited (WoocommerceWidgetEnvironments* self, const gchar* path, const gchar* new_text);
void woocommerce_widget_environments_OnTableNameEdited (WoocommerceWidgetEnvironments* self, const gchar* path, const gchar* new_text);
void woocommerce_widget_environments_OnButtonNewTableClicked (WoocommerceWidgetEnvironments* self);
void woocommerce_widget_environments_OnButtonDeleteTableClicked (WoocommerceWidgetEnvironments* self);
GType woocommerce_restaurant_helper_get_type (void) G_GNUC_CONST;
GeeArrayList* woocommerce_restaurant_helper_GetEnvironments (void);
GeeArrayList* woocommerce_restaurant_helper_GetTables (gint env_id);
gboolean woocommerce_restaurant_helper_DeleteEnvironment (gint env_id);
gboolean woocommerce_restaurant_helper_DeleteTable (gint table_id);
GeeArrayList* woocommerce_restaurant_helper_GetOptions (void);
WoocommerceRestaurantHelper* woocommerce_restaurant_helper_new (void);
WoocommerceRestaurantHelper* woocommerce_restaurant_helper_construct (GType object_type);
GType woocommerce_widget_restautant_options_get_type (void) G_GNUC_CONST;
WoocommerceWidgetRestautantOptions* woocommerce_widget_restautant_options_new (void);
WoocommerceWidgetRestautantOptions* woocommerce_widget_restautant_options_construct (GType object_type);
void woocommerce_widget_restautant_options_Build (WoocommerceWidgetRestautantOptions* self);
void woocommerce_widget_restautant_options_SetEvents (WoocommerceWidgetRestautantOptions* self);


G_END_DECLS

#endif
