/* Modules.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __MODULES_H__
#define __MODULES_H__

#include <glib.h>
#include <GtkSinticBolivia.h>
#include <SinticBolivia.h>
#include <gtk/gtk.h>
#include <gmodule.h>

G_BEGIN_DECLS


#define WOOCOMMERCE_TYPE_SB_MODULEMODULES (woocommerce_sb_modulemodules_get_type ())
#define WOOCOMMERCE_SB_MODULEMODULES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_SB_MODULEMODULES, WoocommerceSB_ModuleModules))
#define WOOCOMMERCE_SB_MODULEMODULES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_SB_MODULEMODULES, WoocommerceSB_ModuleModulesClass))
#define WOOCOMMERCE_IS_SB_MODULEMODULES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_SB_MODULEMODULES))
#define WOOCOMMERCE_IS_SB_MODULEMODULES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_SB_MODULEMODULES))
#define WOOCOMMERCE_SB_MODULEMODULES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_SB_MODULEMODULES, WoocommerceSB_ModuleModulesClass))

typedef struct _WoocommerceSB_ModuleModules WoocommerceSB_ModuleModules;
typedef struct _WoocommerceSB_ModuleModulesClass WoocommerceSB_ModuleModulesClass;
typedef struct _WoocommerceSB_ModuleModulesPrivate WoocommerceSB_ModuleModulesPrivate;

#define WOOCOMMERCE_TYPE_WIDGET_MODULES (woocommerce_widget_modules_get_type ())
#define WOOCOMMERCE_WIDGET_MODULES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_WIDGET_MODULES, WoocommerceWidgetModules))
#define WOOCOMMERCE_WIDGET_MODULES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_WIDGET_MODULES, WoocommerceWidgetModulesClass))
#define WOOCOMMERCE_IS_WIDGET_MODULES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_WIDGET_MODULES))
#define WOOCOMMERCE_IS_WIDGET_MODULES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_WIDGET_MODULES))
#define WOOCOMMERCE_WIDGET_MODULES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_WIDGET_MODULES, WoocommerceWidgetModulesClass))

typedef struct _WoocommerceWidgetModules WoocommerceWidgetModules;
typedef struct _WoocommerceWidgetModulesClass WoocommerceWidgetModulesClass;
typedef struct _WoocommerceWidgetModulesPrivate WoocommerceWidgetModulesPrivate;

struct _WoocommerceSB_ModuleModules {
	SinticBoliviaGtkSBGtkModule parent_instance;
	WoocommerceSB_ModuleModulesPrivate * priv;
};

struct _WoocommerceSB_ModuleModulesClass {
	SinticBoliviaGtkSBGtkModuleClass parent_class;
};

struct _WoocommerceWidgetModules {
	GtkBox parent_instance;
	WoocommerceWidgetModulesPrivate * priv;
	GtkBox* headerBox;
	GtkImage* headerImage;
	GtkLabel* headerLabel;
	GtkBox* buttonsBox;
	GtkButton* buttonEnable;
	GtkButton* buttonDisable;
	GtkScrolledWindow* scrolled;
	GtkTreeView* treeview;
	GtkBox* footerButtonsBox;
	GtkButton* buttonClose;
};

struct _WoocommerceWidgetModulesClass {
	GtkBoxClass parent_class;
};


GType woocommerce_sb_modulemodules_get_type (void) G_GNUC_CONST;
void woocommerce_sb_modulemodules_AddHooks (WoocommerceSB_ModuleModules* self);
void woocommerce_sb_modulemodules_init_menu_management (SinticBoliviaSBModuleArgs* args);
WoocommerceSB_ModuleModules* woocommerce_sb_modulemodules_new (void);
WoocommerceSB_ModuleModules* woocommerce_sb_modulemodules_construct (GType object_type);
GType sb_get_module_type (GModule* customers_module);
GType woocommerce_widget_modules_get_type (void) G_GNUC_CONST;
WoocommerceWidgetModules* woocommerce_widget_modules_new (void);
WoocommerceWidgetModules* woocommerce_widget_modules_construct (GType object_type);
void woocommerce_widget_modules_Build (WoocommerceWidgetModules* self);
void woocommerce_widget_modules_SetEvents (WoocommerceWidgetModules* self);
void woocommerce_widget_modules_RetrieveModules (WoocommerceWidgetModules* self);
void woocommerce_widget_modules_OnTreeViewCursorChanged (WoocommerceWidgetModules* self);
void woocommerce_widget_modules_OnButtonEnableClicked (WoocommerceWidgetModules* self);
void woocommerce_widget_modules_OnButtonDisableClicked (WoocommerceWidgetModules* self);


G_END_DECLS

#endif
