/* Users.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __USERS_H__
#define __USERS_H__

#include <glib.h>
#include <GtkSinticBolivia.h>
#include <SinticBolivia.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <gmodule.h>
#include <glib-object.h>

G_BEGIN_DECLS


#define WOOCOMMERCE_TYPE_SB_MODULEUSERS (woocommerce_sb_moduleusers_get_type ())
#define WOOCOMMERCE_SB_MODULEUSERS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_SB_MODULEUSERS, WoocommerceSB_ModuleUsers))
#define WOOCOMMERCE_SB_MODULEUSERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_SB_MODULEUSERS, WoocommerceSB_ModuleUsersClass))
#define WOOCOMMERCE_IS_SB_MODULEUSERS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_SB_MODULEUSERS))
#define WOOCOMMERCE_IS_SB_MODULEUSERS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_SB_MODULEUSERS))
#define WOOCOMMERCE_SB_MODULEUSERS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_SB_MODULEUSERS, WoocommerceSB_ModuleUsersClass))

typedef struct _WoocommerceSB_ModuleUsers WoocommerceSB_ModuleUsers;
typedef struct _WoocommerceSB_ModuleUsersClass WoocommerceSB_ModuleUsersClass;
typedef struct _WoocommerceSB_ModuleUsersPrivate WoocommerceSB_ModuleUsersPrivate;

#define WOOCOMMERCE_TYPE_WINDOW_LOGIN (woocommerce_window_login_get_type ())
#define WOOCOMMERCE_WINDOW_LOGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_WINDOW_LOGIN, WoocommerceWindowLogin))
#define WOOCOMMERCE_WINDOW_LOGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_WINDOW_LOGIN, WoocommerceWindowLoginClass))
#define WOOCOMMERCE_IS_WINDOW_LOGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_WINDOW_LOGIN))
#define WOOCOMMERCE_IS_WINDOW_LOGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_WINDOW_LOGIN))
#define WOOCOMMERCE_WINDOW_LOGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_WINDOW_LOGIN, WoocommerceWindowLoginClass))

typedef struct _WoocommerceWindowLogin WoocommerceWindowLogin;
typedef struct _WoocommerceWindowLoginClass WoocommerceWindowLoginClass;
typedef struct _WoocommerceWindowLoginPrivate WoocommerceWindowLoginPrivate;

#define WOOCOMMERCE_TYPE_SB_USERS_HELPER (woocommerce_sb_users_helper_get_type ())
#define WOOCOMMERCE_SB_USERS_HELPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_SB_USERS_HELPER, WoocommerceSBUsersHelper))
#define WOOCOMMERCE_SB_USERS_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_SB_USERS_HELPER, WoocommerceSBUsersHelperClass))
#define WOOCOMMERCE_IS_SB_USERS_HELPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_SB_USERS_HELPER))
#define WOOCOMMERCE_IS_SB_USERS_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_SB_USERS_HELPER))
#define WOOCOMMERCE_SB_USERS_HELPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_SB_USERS_HELPER, WoocommerceSBUsersHelperClass))

typedef struct _WoocommerceSBUsersHelper WoocommerceSBUsersHelper;
typedef struct _WoocommerceSBUsersHelperClass WoocommerceSBUsersHelperClass;
typedef struct _WoocommerceSBUsersHelperPrivate WoocommerceSBUsersHelperPrivate;

struct _WoocommerceSB_ModuleUsers {
	SinticBoliviaGtkSBGtkModule parent_instance;
	WoocommerceSB_ModuleUsersPrivate * priv;
};

struct _WoocommerceSB_ModuleUsersClass {
	SinticBoliviaGtkSBGtkModuleClass parent_class;
};

struct _WoocommerceWindowLogin {
	GtkWindow parent_instance;
	WoocommerceWindowLoginPrivate * priv;
	GtkBuilder* ui;
	GtkFixed* fixed1;
	GtkBox* box1;
	GtkEventBox* eventbox1;
	GtkBox* boxFooter;
	GtkEntry* entryUsername;
	GtkEntry* entryPassword;
	GtkButton* buttonSignIn;
	GtkButton* buttonCancel;
	gint currentImg;
	guint timeoutId;
};

struct _WoocommerceWindowLoginClass {
	GtkWindowClass parent_class;
};

struct _WoocommerceSBUsersHelper {
	GTypeInstance parent_instance;
	volatile int ref_count;
	WoocommerceSBUsersHelperPrivate * priv;
};

struct _WoocommerceSBUsersHelperClass {
	GTypeClass parent_class;
	void (*finalize) (WoocommerceSBUsersHelper *self);
};


GType woocommerce_sb_moduleusers_get_type (void) G_GNUC_CONST;
void woocommerce_sb_moduleusers_init_menu_management (SinticBoliviaSBModuleArgs* args);
void woocommerce_sb_moduleusers_local_authentication (SinticBoliviaSBModuleArgs* args);
void woocommerce_sb_moduleusers_login_dialog (SinticBoliviaSBModuleArgs* args);
WoocommerceSB_ModuleUsers* woocommerce_sb_moduleusers_new (void);
WoocommerceSB_ModuleUsers* woocommerce_sb_moduleusers_construct (GType object_type);
GType sb_get_module_type (GModule* users_module);
GType woocommerce_window_login_get_type (void) G_GNUC_CONST;
WoocommerceWindowLogin* woocommerce_window_login_new (void);
WoocommerceWindowLogin* woocommerce_window_login_construct (GType object_type);
void woocommerce_window_login_Build (WoocommerceWindowLogin* self);
void woocommerce_window_login_SetEvents (WoocommerceWindowLogin* self);
void woocommerce_window_login_OnButtonLoginClicked (WoocommerceWindowLogin* self);
gpointer woocommerce_sb_users_helper_ref (gpointer instance);
void woocommerce_sb_users_helper_unref (gpointer instance);
GParamSpec* woocommerce_param_spec_sb_users_helper (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void woocommerce_value_set_sb_users_helper (GValue* value, gpointer v_object);
void woocommerce_value_take_sb_users_helper (GValue* value, gpointer v_object);
gpointer woocommerce_value_get_sb_users_helper (const GValue* value);
GType woocommerce_sb_users_helper_get_type (void) G_GNUC_CONST;
GList* woocommerce_sb_users_helper_GetRoles (void);
WoocommerceSBUsersHelper* woocommerce_sb_users_helper_new (void);
WoocommerceSBUsersHelper* woocommerce_sb_users_helper_construct (GType object_type);


G_END_DECLS

#endif
