/* class.role.c generated by valac 0.24.0, the Vala compiler
 * generated from class.role.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SinticBolivia.h>
#include <stdlib.h>
#include <string.h>


#define WOOCOMMERCE_TYPE_SB_ROLE (woocommerce_sb_role_get_type ())
#define WOOCOMMERCE_SB_ROLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_SB_ROLE, WoocommerceSBRole))
#define WOOCOMMERCE_SB_ROLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_SB_ROLE, WoocommerceSBRoleClass))
#define WOOCOMMERCE_IS_SB_ROLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_SB_ROLE))
#define WOOCOMMERCE_IS_SB_ROLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_SB_ROLE))
#define WOOCOMMERCE_SB_ROLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_SB_ROLE, WoocommerceSBRoleClass))

typedef struct _WoocommerceSBRole WoocommerceSBRole;
typedef struct _WoocommerceSBRoleClass WoocommerceSBRoleClass;
typedef struct _WoocommerceSBRolePrivate WoocommerceSBRolePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block5Data Block5Data;

struct _WoocommerceSBRole {
	GObject parent_instance;
	WoocommerceSBRolePrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
	GList* permissions;
};

struct _WoocommerceSBRoleClass {
	GObjectClass parent_class;
};

struct _Block5Data {
	int _ref_count_;
	WoocommerceSBRole* self;
	gboolean exist;
	gchar* perm;
};


static gpointer woocommerce_sb_role_parent_class = NULL;

GType woocommerce_sb_role_get_type (void) G_GNUC_CONST;
enum  {
	WOOCOMMERCE_SB_ROLE_DUMMY_PROPERTY,
	WOOCOMMERCE_SB_ROLE_ID,
	WOOCOMMERCE_SB_ROLE_NAME
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
WoocommerceSBRole* woocommerce_sb_role_new (void);
WoocommerceSBRole* woocommerce_sb_role_construct (GType object_type);
WoocommerceSBRole* woocommerce_sb_role_new_from_id (gint role_id);
WoocommerceSBRole* woocommerce_sb_role_construct_from_id (GType object_type, gint role_id);
void woocommerce_sb_role_GetDbData (WoocommerceSBRole* self, gint rid);
void woocommerce_sb_role_SetDbData (WoocommerceSBRole* self, SinticBoliviaDatabaseSBDBRow* row);
gboolean woocommerce_sb_role_HasPermission (WoocommerceSBRole* self, const gchar* perm);
static Block5Data* block5_data_ref (Block5Data* _data5_);
static void block5_data_unref (void * _userdata_);
static void __lambda10_ (Block5Data* _data5_, const gchar* entry);
static void ___lambda10__gfunc (gconstpointer data, gpointer self);
gint woocommerce_sb_role_get_Id (WoocommerceSBRole* self);
const gchar* woocommerce_sb_role_get_Name (WoocommerceSBRole* self);
static void woocommerce_sb_role_finalize (GObject* obj);
static void _vala_woocommerce_sb_role_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


WoocommerceSBRole* woocommerce_sb_role_construct (GType object_type) {
	WoocommerceSBRole * self = NULL;
	self = (WoocommerceSBRole*) g_object_new (object_type, NULL);
	__g_list_free__g_free0_0 (self->permissions);
	self->permissions = NULL;
	return self;
}


WoocommerceSBRole* woocommerce_sb_role_new (void) {
	return woocommerce_sb_role_construct (WOOCOMMERCE_TYPE_SB_ROLE);
}


WoocommerceSBRole* woocommerce_sb_role_construct_from_id (GType object_type, gint role_id) {
	WoocommerceSBRole * self = NULL;
	gint _tmp0_ = 0;
	self = (WoocommerceSBRole*) woocommerce_sb_role_construct (object_type);
	_tmp0_ = role_id;
	woocommerce_sb_role_GetDbData (self, _tmp0_);
	return self;
}


WoocommerceSBRole* woocommerce_sb_role_new_from_id (gint role_id) {
	return woocommerce_sb_role_construct_from_id (WOOCOMMERCE_TYPE_SB_ROLE, role_id);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void woocommerce_sb_role_GetDbData (WoocommerceSBRole* self, gint rid) {
	SinticBoliviaDatabaseSBDatabase* dbh = NULL;
	GObject* _tmp0_ = NULL;
	gchar* query = NULL;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	SinticBoliviaDatabaseSBDatabase* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	glong _tmp5_ = 0L;
	SinticBoliviaDatabaseSBDatabase* _tmp6_ = NULL;
	SinticBoliviaDatabaseSBDBRow** _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	SinticBoliviaDatabaseSBDBRow** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	SinticBoliviaDatabaseSBDBRow* _tmp9_ = NULL;
	SinticBoliviaDatabaseSBDBRow* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gchar* _tmp14_ = NULL;
	SinticBoliviaDatabaseSBDatabase* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	glong _tmp17_ = 0L;
	SinticBoliviaDatabaseSBDatabase* _tmp18_ = NULL;
	SinticBoliviaDatabaseSBDBRow** _tmp19_ = NULL;
	gint _tmp19__length1 = 0;
	SinticBoliviaDatabaseSBDBRow** _tmp20_ = NULL;
	gint _tmp20__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = sintic_bolivia_sb_globals_GetVar ("dbh");
	dbh = G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SINTIC_BOLIVIA_DATABASE_TYPE_SB_DATABASE, SinticBoliviaDatabaseSBDatabase);
	_tmp1_ = rid;
	_tmp2_ = g_strdup_printf ("SELECT * FROM user_roles WHERE role_id = %d LIMIT 1", _tmp1_);
	query = _tmp2_;
	_tmp3_ = dbh;
	_tmp4_ = query;
	_tmp5_ = sintic_bolivia_database_sb_database_Query (_tmp3_, _tmp4_);
	if (_tmp5_ <= ((glong) 0)) {
		_g_free0 (query);
		_g_object_unref0 (dbh);
		return;
	}
	_tmp6_ = dbh;
	_tmp7_ = sintic_bolivia_database_sb_database_get_Rows (_tmp6_, &_tmp7__length1);
	_tmp8_ = _tmp7_;
	_tmp8__length1 = _tmp7__length1;
	_tmp9_ = _tmp8_[0];
	_tmp10_ = _g_object_ref0 (_tmp9_);
	_g_object_unref0 (self->dbData);
	self->dbData = _tmp10_;
	_tmp11_ = g_strdup ("SELECT * FROM permissions p, role2permission r2p " "WHERE p.permission_id = r2p.permission_id " "AND r2p.role_id = %d");
	_g_free0 (query);
	query = _tmp11_;
	_tmp12_ = query;
	_tmp13_ = rid;
	_tmp14_ = g_strdup_printf (_tmp12_, _tmp13_);
	_g_free0 (query);
	query = _tmp14_;
	_tmp15_ = dbh;
	_tmp16_ = query;
	_tmp17_ = sintic_bolivia_database_sb_database_Query (_tmp15_, _tmp16_);
	if (_tmp17_ <= ((glong) 0)) {
		_g_free0 (query);
		_g_object_unref0 (dbh);
		return;
	}
	_tmp18_ = dbh;
	_tmp19_ = sintic_bolivia_database_sb_database_get_Rows (_tmp18_, &_tmp19__length1);
	_tmp20_ = _tmp19_;
	_tmp20__length1 = _tmp19__length1;
	{
		SinticBoliviaDatabaseSBDBRow** row_collection = NULL;
		gint row_collection_length1 = 0;
		gint _row_collection_size_ = 0;
		gint row_it = 0;
		row_collection = _tmp20_;
		row_collection_length1 = _tmp20__length1;
		for (row_it = 0; row_it < _tmp20__length1; row_it = row_it + 1) {
			SinticBoliviaDatabaseSBDBRow* _tmp21_ = NULL;
			SinticBoliviaDatabaseSBDBRow* row = NULL;
			_tmp21_ = _g_object_ref0 (row_collection[row_it]);
			row = _tmp21_;
			{
				SinticBoliviaDatabaseSBDBRow* _tmp22_ = NULL;
				const gchar* _tmp23_ = NULL;
				gchar* _tmp24_ = NULL;
				_tmp22_ = row;
				_tmp23_ = sintic_bolivia_database_sbdb_row_Get (_tmp22_, "permission");
				_tmp24_ = g_strdup (_tmp23_);
				self->permissions = g_list_append (self->permissions, _tmp24_);
				_g_object_unref0 (row);
			}
		}
	}
	_g_free0 (query);
	_g_object_unref0 (dbh);
}


void woocommerce_sb_role_SetDbData (WoocommerceSBRole* self, SinticBoliviaDatabaseSBDBRow* row) {
	SinticBoliviaDatabaseSBDBRow* _tmp0_ = NULL;
	SinticBoliviaDatabaseSBDBRow* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (row != NULL);
	_tmp0_ = row;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->dbData);
	self->dbData = _tmp1_;
}


static Block5Data* block5_data_ref (Block5Data* _data5_) {
	g_atomic_int_inc (&_data5_->_ref_count_);
	return _data5_;
}


static void block5_data_unref (void * _userdata_) {
	Block5Data* _data5_;
	_data5_ = (Block5Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data5_->_ref_count_)) {
		WoocommerceSBRole* self;
		self = _data5_->self;
		_g_free0 (_data5_->perm);
		_g_object_unref0 (self);
		g_slice_free (Block5Data, _data5_);
	}
}


static void __lambda10_ (Block5Data* _data5_, const gchar* entry) {
	WoocommerceSBRole* self;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	self = _data5_->self;
	g_return_if_fail (entry != NULL);
	_tmp0_ = entry;
	_tmp1_ = _data5_->perm;
	if (g_strcmp0 (_tmp0_, _tmp1_) == 0) {
		_data5_->exist = TRUE;
	}
}


static void ___lambda10__gfunc (gconstpointer data, gpointer self) {
	__lambda10_ (self, (const gchar*) data);
}


gboolean woocommerce_sb_role_HasPermission (WoocommerceSBRole* self, const gchar* perm) {
	gboolean result = FALSE;
	Block5Data* _data5_;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (perm != NULL, FALSE);
	_data5_ = g_slice_new0 (Block5Data);
	_data5_->_ref_count_ = 1;
	_data5_->self = g_object_ref (self);
	_tmp0_ = perm;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (_data5_->perm);
	_data5_->perm = _tmp1_;
	_data5_->exist = FALSE;
	_tmp2_ = self->permissions;
	g_list_foreach (_tmp2_, ___lambda10__gfunc, _data5_);
	result = _data5_->exist;
	block5_data_unref (_data5_);
	_data5_ = NULL;
	return result;
}


gint woocommerce_sb_role_get_Id (WoocommerceSBRole* self) {
	gint result;
	SinticBoliviaDatabaseSBDBRow* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->dbData;
	_tmp1_ = sintic_bolivia_database_sbdb_row_Get (_tmp0_, "role_id");
	_tmp2_ = atoi (_tmp1_);
	result = _tmp2_;
	return result;
}


const gchar* woocommerce_sb_role_get_Name (WoocommerceSBRole* self) {
	const gchar* result;
	SinticBoliviaDatabaseSBDBRow* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->dbData;
	_tmp1_ = sintic_bolivia_database_sbdb_row_Get (_tmp0_, "role_name");
	result = _tmp1_;
	return result;
}


static void woocommerce_sb_role_class_init (WoocommerceSBRoleClass * klass) {
	woocommerce_sb_role_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_woocommerce_sb_role_get_property;
	G_OBJECT_CLASS (klass)->finalize = woocommerce_sb_role_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), WOOCOMMERCE_SB_ROLE_ID, g_param_spec_int ("Id", "Id", "Id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), WOOCOMMERCE_SB_ROLE_NAME, g_param_spec_string ("Name", "Name", "Name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void woocommerce_sb_role_instance_init (WoocommerceSBRole * self) {
}


static void woocommerce_sb_role_finalize (GObject* obj) {
	WoocommerceSBRole * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WOOCOMMERCE_TYPE_SB_ROLE, WoocommerceSBRole);
	_g_object_unref0 (self->dbData);
	__g_list_free__g_free0_0 (self->permissions);
	G_OBJECT_CLASS (woocommerce_sb_role_parent_class)->finalize (obj);
}


GType woocommerce_sb_role_get_type (void) {
	static volatile gsize woocommerce_sb_role_type_id__volatile = 0;
	if (g_once_init_enter (&woocommerce_sb_role_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WoocommerceSBRoleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) woocommerce_sb_role_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WoocommerceSBRole), 0, (GInstanceInitFunc) woocommerce_sb_role_instance_init, NULL };
		GType woocommerce_sb_role_type_id;
		woocommerce_sb_role_type_id = g_type_register_static (G_TYPE_OBJECT, "WoocommerceSBRole", &g_define_type_info, 0);
		g_once_init_leave (&woocommerce_sb_role_type_id__volatile, woocommerce_sb_role_type_id);
	}
	return woocommerce_sb_role_type_id__volatile;
}


static void _vala_woocommerce_sb_role_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	WoocommerceSBRole * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WOOCOMMERCE_TYPE_SB_ROLE, WoocommerceSBRole);
	switch (property_id) {
		case WOOCOMMERCE_SB_ROLE_ID:
		g_value_set_int (value, woocommerce_sb_role_get_Id (self));
		break;
		case WOOCOMMERCE_SB_ROLE_NAME:
		g_value_set_string (value, woocommerce_sb_role_get_Name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



