/* .h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef ___H__
#define ___H__

#include <glib.h>
#include <glib-object.h>
#include <SinticBolivia.h>
#include <gtk/gtk.h>
#include <gmodule.h>

G_BEGIN_DECLS


#define WOOCOMMERCE_TYPE_SB_MODULEINVENTORY (woocommerce_sb_moduleinventory_get_type ())
#define WOOCOMMERCE_SB_MODULEINVENTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_SB_MODULEINVENTORY, WoocommerceSB_ModuleInventory))
#define WOOCOMMERCE_SB_MODULEINVENTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_SB_MODULEINVENTORY, WoocommerceSB_ModuleInventoryClass))
#define WOOCOMMERCE_IS_SB_MODULEINVENTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_SB_MODULEINVENTORY))
#define WOOCOMMERCE_IS_SB_MODULEINVENTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_SB_MODULEINVENTORY))
#define WOOCOMMERCE_SB_MODULEINVENTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_SB_MODULEINVENTORY, WoocommerceSB_ModuleInventoryClass))

typedef struct _WoocommerceSB_ModuleInventory WoocommerceSB_ModuleInventory;
typedef struct _WoocommerceSB_ModuleInventoryClass WoocommerceSB_ModuleInventoryClass;
typedef struct _WoocommerceSB_ModuleInventoryPrivate WoocommerceSB_ModuleInventoryPrivate;

struct _WoocommerceSB_ModuleInventory {
	GObject parent_instance;
	WoocommerceSB_ModuleInventoryPrivate * priv;
};

struct _WoocommerceSB_ModuleInventoryClass {
	GObjectClass parent_class;
};


GType woocommerce_sb_moduleinventory_get_type (void) G_GNUC_CONST;
void woocommerce_sb_moduleinventory_sidebar_init (SinticBoliviaSBModuleArgs* harg);
WoocommerceSB_ModuleInventory* woocommerce_sb_moduleinventory_new (void);
WoocommerceSB_ModuleInventory* woocommerce_sb_moduleinventory_construct (GType object_type);
GType sb_get_module_type (GModule* inventory_module);


G_END_DECLS

#endif
