/* Inventory.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __INVENTORY_H__
#define __INVENTORY_H__

#include <glib.h>
#include <GtkSinticBolivia.h>
#include <SinticBolivia.h>
#include <gee.h>
#include <gtk/gtk.h>
#include <gmodule.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <hpdf.h>
#include <cairo.h>
#include <gdk/gdk.h>

G_BEGIN_DECLS


#define EPOS_TYPE_SB_MODULEINVENTORY (epos_sb_moduleinventory_get_type ())
#define EPOS_SB_MODULEINVENTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_SB_MODULEINVENTORY, EPosSB_ModuleInventory))
#define EPOS_SB_MODULEINVENTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_SB_MODULEINVENTORY, EPosSB_ModuleInventoryClass))
#define EPOS_IS_SB_MODULEINVENTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_SB_MODULEINVENTORY))
#define EPOS_IS_SB_MODULEINVENTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_SB_MODULEINVENTORY))
#define EPOS_SB_MODULEINVENTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_SB_MODULEINVENTORY, EPosSB_ModuleInventoryClass))

typedef struct _EPosSB_ModuleInventory EPosSB_ModuleInventory;
typedef struct _EPosSB_ModuleInventoryClass EPosSB_ModuleInventoryClass;
typedef struct _EPosSB_ModuleInventoryPrivate EPosSB_ModuleInventoryPrivate;

#define EPOS_TYPE_EASSEMBLY_COMPONENT (epos_eassembly_component_get_type ())
#define EPOS_EASSEMBLY_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_EASSEMBLY_COMPONENT, EPosEAssemblyComponent))
#define EPOS_EASSEMBLY_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_EASSEMBLY_COMPONENT, EPosEAssemblyComponentClass))
#define EPOS_IS_EASSEMBLY_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_EASSEMBLY_COMPONENT))
#define EPOS_IS_EASSEMBLY_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_EASSEMBLY_COMPONENT))
#define EPOS_EASSEMBLY_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_EASSEMBLY_COMPONENT, EPosEAssemblyComponentClass))

typedef struct _EPosEAssemblyComponent EPosEAssemblyComponent;
typedef struct _EPosEAssemblyComponentClass EPosEAssemblyComponentClass;
typedef struct _EPosEAssemblyComponentPrivate EPosEAssemblyComponentPrivate;

#define EPOS_TYPE_EPRODUCT (epos_eproduct_get_type ())
#define EPOS_EPRODUCT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_EPRODUCT, EPosEProduct))
#define EPOS_EPRODUCT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_EPRODUCT, EPosEProductClass))
#define EPOS_IS_EPRODUCT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_EPRODUCT))
#define EPOS_IS_EPRODUCT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_EPRODUCT))
#define EPOS_EPRODUCT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_EPRODUCT, EPosEProductClass))

typedef struct _EPosEProduct EPosEProduct;
typedef struct _EPosEProductClass EPosEProductClass;

#define EPOS_TYPE_EASSEMBLY (epos_eassembly_get_type ())
#define EPOS_EASSEMBLY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_EASSEMBLY, EPosEAssembly))
#define EPOS_EASSEMBLY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_EASSEMBLY, EPosEAssemblyClass))
#define EPOS_IS_EASSEMBLY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_EASSEMBLY))
#define EPOS_IS_EASSEMBLY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_EASSEMBLY))
#define EPOS_EASSEMBLY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_EASSEMBLY, EPosEAssemblyClass))

typedef struct _EPosEAssembly EPosEAssembly;
typedef struct _EPosEAssemblyClass EPosEAssemblyClass;
typedef struct _EPosEAssemblyPrivate EPosEAssemblyPrivate;

#define EPOS_TYPE_CATALOG (epos_catalog_get_type ())
#define EPOS_CATALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_CATALOG, EPosCatalog))
#define EPOS_CATALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_CATALOG, EPosCatalogClass))
#define EPOS_IS_CATALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_CATALOG))
#define EPOS_IS_CATALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_CATALOG))
#define EPOS_CATALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_CATALOG, EPosCatalogClass))

typedef struct _EPosCatalog EPosCatalog;
typedef struct _EPosCatalogClass EPosCatalogClass;
typedef struct _EPosCatalogPrivate EPosCatalogPrivate;

#define EPOS_TYPE_ORDER (epos_order_get_type ())
#define EPOS_ORDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_ORDER, EPosOrder))
#define EPOS_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_ORDER, EPosOrderClass))
#define EPOS_IS_ORDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_ORDER))
#define EPOS_IS_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_ORDER))
#define EPOS_ORDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_ORDER, EPosOrderClass))

typedef struct _EPosOrder EPosOrder;
typedef struct _EPosOrderClass EPosOrderClass;
typedef struct _EPosOrderPrivate EPosOrderPrivate;

#define EPOS_TYPE_PDF_CELL (epos_pdf_cell_get_type ())
#define EPOS_PDF_CELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_PDF_CELL, EPosPdfCell))
#define EPOS_PDF_CELL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_PDF_CELL, EPosPdfCellClass))
#define EPOS_IS_PDF_CELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_PDF_CELL))
#define EPOS_IS_PDF_CELL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_PDF_CELL))
#define EPOS_PDF_CELL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_PDF_CELL, EPosPdfCellClass))

typedef struct _EPosPdfCell EPosPdfCell;
typedef struct _EPosPdfCellClass EPosPdfCellClass;
typedef struct _EPosPdfCellPrivate EPosPdfCellPrivate;

#define EPOS_TYPE_PDF_ROW (epos_pdf_row_get_type ())
#define EPOS_PDF_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_PDF_ROW, EPosPdfRow))
#define EPOS_PDF_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_PDF_ROW, EPosPdfRowClass))
#define EPOS_IS_PDF_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_PDF_ROW))
#define EPOS_IS_PDF_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_PDF_ROW))
#define EPOS_PDF_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_PDF_ROW, EPosPdfRowClass))

typedef struct _EPosPdfRow EPosPdfRow;
typedef struct _EPosPdfRowClass EPosPdfRowClass;
typedef struct _EPosPdfRowPrivate EPosPdfRowPrivate;

#define EPOS_TYPE_PDF_TABLE (epos_pdf_table_get_type ())
#define EPOS_PDF_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_PDF_TABLE, EPosPdfTable))
#define EPOS_PDF_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_PDF_TABLE, EPosPdfTableClass))
#define EPOS_IS_PDF_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_PDF_TABLE))
#define EPOS_IS_PDF_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_PDF_TABLE))
#define EPOS_PDF_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_PDF_TABLE, EPosPdfTableClass))

typedef struct _EPosPdfTable EPosPdfTable;
typedef struct _EPosPdfTableClass EPosPdfTableClass;
typedef struct _EPosPdfTablePrivate EPosPdfTablePrivate;
typedef struct _EPosEProductPrivate EPosEProductPrivate;

#define EPOS_TYPE_EPURCHASE_ORDER_ITEM (epos_epurchase_order_item_get_type ())
#define EPOS_EPURCHASE_ORDER_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_EPURCHASE_ORDER_ITEM, EPosEPurchaseOrderItem))
#define EPOS_EPURCHASE_ORDER_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_EPURCHASE_ORDER_ITEM, EPosEPurchaseOrderItemClass))
#define EPOS_IS_EPURCHASE_ORDER_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_EPURCHASE_ORDER_ITEM))
#define EPOS_IS_EPURCHASE_ORDER_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_EPURCHASE_ORDER_ITEM))
#define EPOS_EPURCHASE_ORDER_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_EPURCHASE_ORDER_ITEM, EPosEPurchaseOrderItemClass))

typedef struct _EPosEPurchaseOrderItem EPosEPurchaseOrderItem;
typedef struct _EPosEPurchaseOrderItemClass EPosEPurchaseOrderItemClass;
typedef struct _EPosEPurchaseOrderItemPrivate EPosEPurchaseOrderItemPrivate;

#define EPOS_TYPE_PURCHASE_ORDER (epos_purchase_order_get_type ())
#define EPOS_PURCHASE_ORDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_PURCHASE_ORDER, EPosPurchaseOrder))
#define EPOS_PURCHASE_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_PURCHASE_ORDER, EPosPurchaseOrderClass))
#define EPOS_IS_PURCHASE_ORDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_PURCHASE_ORDER))
#define EPOS_IS_PURCHASE_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_PURCHASE_ORDER))
#define EPOS_PURCHASE_ORDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_PURCHASE_ORDER, EPosPurchaseOrderClass))

typedef struct _EPosPurchaseOrder EPosPurchaseOrder;
typedef struct _EPosPurchaseOrderClass EPosPurchaseOrderClass;
typedef struct _EPosPurchaseOrderPrivate EPosPurchaseOrderPrivate;

#define WOOCOMMERCE_TYPE_SALE (woocommerce_sale_get_type ())
#define WOOCOMMERCE_SALE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_TYPE_SALE, WoocommerceSale))
#define WOOCOMMERCE_SALE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_TYPE_SALE, WoocommerceSaleClass))
#define WOOCOMMERCE_IS_SALE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_TYPE_SALE))
#define WOOCOMMERCE_IS_SALE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_TYPE_SALE))
#define WOOCOMMERCE_SALE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_TYPE_SALE, WoocommerceSaleClass))

typedef struct _WoocommerceSale WoocommerceSale;
typedef struct _WoocommerceSaleClass WoocommerceSaleClass;
typedef struct _WoocommerceSalePrivate WoocommerceSalePrivate;

#define EPOS_TYPE_ESUPPLIER (epos_esupplier_get_type ())
#define EPOS_ESUPPLIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_ESUPPLIER, EPosESupplier))
#define EPOS_ESUPPLIER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_ESUPPLIER, EPosESupplierClass))
#define EPOS_IS_ESUPPLIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_ESUPPLIER))
#define EPOS_IS_ESUPPLIER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_ESUPPLIER))
#define EPOS_ESUPPLIER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_ESUPPLIER, EPosESupplierClass))

typedef struct _EPosESupplier EPosESupplier;
typedef struct _EPosESupplierClass EPosESupplierClass;
typedef struct _EPosESupplierPrivate EPosESupplierPrivate;

#define EPOS_TYPE_ETAX_RATE (epos_etax_rate_get_type ())
#define EPOS_ETAX_RATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_ETAX_RATE, EPosETaxRate))
#define EPOS_ETAX_RATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_ETAX_RATE, EPosETaxRateClass))
#define EPOS_IS_ETAX_RATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_ETAX_RATE))
#define EPOS_IS_ETAX_RATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_ETAX_RATE))
#define EPOS_ETAX_RATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_ETAX_RATE, EPosETaxRateClass))

typedef struct _EPosETaxRate EPosETaxRate;
typedef struct _EPosETaxRateClass EPosETaxRateClass;
typedef struct _EPosETaxRatePrivate EPosETaxRatePrivate;

#define WOOCOMMERCE_INVOICE_TYPE_TICKET_INVOICE (woocommerce_invoice_ticket_invoice_get_type ())
#define WOOCOMMERCE_INVOICE_TICKET_INVOICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WOOCOMMERCE_INVOICE_TYPE_TICKET_INVOICE, WoocommerceInvoiceTicketInvoice))
#define WOOCOMMERCE_INVOICE_TICKET_INVOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WOOCOMMERCE_INVOICE_TYPE_TICKET_INVOICE, WoocommerceInvoiceTicketInvoiceClass))
#define WOOCOMMERCE_INVOICE_IS_TICKET_INVOICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WOOCOMMERCE_INVOICE_TYPE_TICKET_INVOICE))
#define WOOCOMMERCE_INVOICE_IS_TICKET_INVOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WOOCOMMERCE_INVOICE_TYPE_TICKET_INVOICE))
#define WOOCOMMERCE_INVOICE_TICKET_INVOICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WOOCOMMERCE_INVOICE_TYPE_TICKET_INVOICE, WoocommerceInvoiceTicketInvoiceClass))

typedef struct _WoocommerceInvoiceTicketInvoice WoocommerceInvoiceTicketInvoice;
typedef struct _WoocommerceInvoiceTicketInvoiceClass WoocommerceInvoiceTicketInvoiceClass;
typedef struct _WoocommerceInvoiceTicketInvoicePrivate WoocommerceInvoiceTicketInvoicePrivate;

#define EPOS_TYPE_WIDGET_ITEM_TYPES (epos_widget_item_types_get_type ())
#define EPOS_WIDGET_ITEM_TYPES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_ITEM_TYPES, EPosWidgetItemTypes))
#define EPOS_WIDGET_ITEM_TYPES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_ITEM_TYPES, EPosWidgetItemTypesClass))
#define EPOS_IS_WIDGET_ITEM_TYPES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_ITEM_TYPES))
#define EPOS_IS_WIDGET_ITEM_TYPES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_ITEM_TYPES))
#define EPOS_WIDGET_ITEM_TYPES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_ITEM_TYPES, EPosWidgetItemTypesClass))

typedef struct _EPosWidgetItemTypes EPosWidgetItemTypes;
typedef struct _EPosWidgetItemTypesClass EPosWidgetItemTypesClass;
typedef struct _EPosWidgetItemTypesPrivate EPosWidgetItemTypesPrivate;

#define EPOS_TYPE_WIDGET_ADJUSTMENTS (epos_widget_adjustments_get_type ())
#define EPOS_WIDGET_ADJUSTMENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_ADJUSTMENTS, EPosWidgetAdjustments))
#define EPOS_WIDGET_ADJUSTMENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_ADJUSTMENTS, EPosWidgetAdjustmentsClass))
#define EPOS_IS_WIDGET_ADJUSTMENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_ADJUSTMENTS))
#define EPOS_IS_WIDGET_ADJUSTMENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_ADJUSTMENTS))
#define EPOS_WIDGET_ADJUSTMENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_ADJUSTMENTS, EPosWidgetAdjustmentsClass))

typedef struct _EPosWidgetAdjustments EPosWidgetAdjustments;
typedef struct _EPosWidgetAdjustmentsClass EPosWidgetAdjustmentsClass;
typedef struct _EPosWidgetAdjustmentsPrivate EPosWidgetAdjustmentsPrivate;

#define EPOS_WIDGET_ADJUSTMENTS_TYPE_COLUMNS (epos_widget_adjustments_columns_get_type ())

#define EPOS_TYPE_WIDGET_ASSEMBLIES (epos_widget_assemblies_get_type ())
#define EPOS_WIDGET_ASSEMBLIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_ASSEMBLIES, EPosWidgetAssemblies))
#define EPOS_WIDGET_ASSEMBLIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_ASSEMBLIES, EPosWidgetAssembliesClass))
#define EPOS_IS_WIDGET_ASSEMBLIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_ASSEMBLIES))
#define EPOS_IS_WIDGET_ASSEMBLIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_ASSEMBLIES))
#define EPOS_WIDGET_ASSEMBLIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_ASSEMBLIES, EPosWidgetAssembliesClass))

typedef struct _EPosWidgetAssemblies EPosWidgetAssemblies;
typedef struct _EPosWidgetAssembliesClass EPosWidgetAssembliesClass;
typedef struct _EPosWidgetAssembliesPrivate EPosWidgetAssembliesPrivate;

#define EPOS_TYPE_WIDGET_CURRENCIES (epos_widget_currencies_get_type ())
#define EPOS_WIDGET_CURRENCIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_CURRENCIES, EPosWidgetCurrencies))
#define EPOS_WIDGET_CURRENCIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_CURRENCIES, EPosWidgetCurrenciesClass))
#define EPOS_IS_WIDGET_CURRENCIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_CURRENCIES))
#define EPOS_IS_WIDGET_CURRENCIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_CURRENCIES))
#define EPOS_WIDGET_CURRENCIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_CURRENCIES, EPosWidgetCurrenciesClass))

typedef struct _EPosWidgetCurrencies EPosWidgetCurrencies;
typedef struct _EPosWidgetCurrenciesClass EPosWidgetCurrenciesClass;
typedef struct _EPosWidgetCurrenciesPrivate EPosWidgetCurrenciesPrivate;

#define EPOS_TYPE_WIDGET_PRODUCT_DEPARTMENTS (epos_widget_product_departments_get_type ())
#define EPOS_WIDGET_PRODUCT_DEPARTMENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_PRODUCT_DEPARTMENTS, EPosWidgetProductDepartments))
#define EPOS_WIDGET_PRODUCT_DEPARTMENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_PRODUCT_DEPARTMENTS, EPosWidgetProductDepartmentsClass))
#define EPOS_IS_WIDGET_PRODUCT_DEPARTMENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_PRODUCT_DEPARTMENTS))
#define EPOS_IS_WIDGET_PRODUCT_DEPARTMENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_PRODUCT_DEPARTMENTS))
#define EPOS_WIDGET_PRODUCT_DEPARTMENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_PRODUCT_DEPARTMENTS, EPosWidgetProductDepartmentsClass))

typedef struct _EPosWidgetProductDepartments EPosWidgetProductDepartments;
typedef struct _EPosWidgetProductDepartmentsClass EPosWidgetProductDepartmentsClass;
typedef struct _EPosWidgetProductDepartmentsPrivate EPosWidgetProductDepartmentsPrivate;

#define EPOS_TYPE_WIDGET_INVENTORY (epos_widget_inventory_get_type ())
#define EPOS_WIDGET_INVENTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_INVENTORY, EPosWidgetInventory))
#define EPOS_WIDGET_INVENTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_INVENTORY, EPosWidgetInventoryClass))
#define EPOS_IS_WIDGET_INVENTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_INVENTORY))
#define EPOS_IS_WIDGET_INVENTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_INVENTORY))
#define EPOS_WIDGET_INVENTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_INVENTORY, EPosWidgetInventoryClass))

typedef struct _EPosWidgetInventory EPosWidgetInventory;
typedef struct _EPosWidgetInventoryClass EPosWidgetInventoryClass;
typedef struct _EPosWidgetInventoryPrivate EPosWidgetInventoryPrivate;

#define EPOS_TYPE_WINDOW_NEW_ASSEMBLY (epos_window_new_assembly_get_type ())
#define EPOS_WINDOW_NEW_ASSEMBLY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WINDOW_NEW_ASSEMBLY, EPosWindowNewAssembly))
#define EPOS_WINDOW_NEW_ASSEMBLY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WINDOW_NEW_ASSEMBLY, EPosWindowNewAssemblyClass))
#define EPOS_IS_WINDOW_NEW_ASSEMBLY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WINDOW_NEW_ASSEMBLY))
#define EPOS_IS_WINDOW_NEW_ASSEMBLY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WINDOW_NEW_ASSEMBLY))
#define EPOS_WINDOW_NEW_ASSEMBLY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WINDOW_NEW_ASSEMBLY, EPosWindowNewAssemblyClass))

typedef struct _EPosWindowNewAssembly EPosWindowNewAssembly;
typedef struct _EPosWindowNewAssemblyClass EPosWindowNewAssemblyClass;
typedef struct _EPosWindowNewAssemblyPrivate EPosWindowNewAssemblyPrivate;

#define EPOS_TYPE_WIDGET_NEW_PRODUCT (epos_widget_new_product_get_type ())
#define EPOS_WIDGET_NEW_PRODUCT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_NEW_PRODUCT, EPosWidgetNewProduct))
#define EPOS_WIDGET_NEW_PRODUCT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_NEW_PRODUCT, EPosWidgetNewProductClass))
#define EPOS_IS_WIDGET_NEW_PRODUCT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_NEW_PRODUCT))
#define EPOS_IS_WIDGET_NEW_PRODUCT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_NEW_PRODUCT))
#define EPOS_WIDGET_NEW_PRODUCT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_NEW_PRODUCT, EPosWidgetNewProductClass))

typedef struct _EPosWidgetNewProduct EPosWidgetNewProduct;
typedef struct _EPosWidgetNewProductClass EPosWidgetNewProductClass;
typedef struct _EPosWidgetNewProductPrivate EPosWidgetNewProductPrivate;

#define EPOS_TYPE_WIDGET_NEW_SUPPLIER (epos_widget_new_supplier_get_type ())
#define EPOS_WIDGET_NEW_SUPPLIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_NEW_SUPPLIER, EPosWidgetNewSupplier))
#define EPOS_WIDGET_NEW_SUPPLIER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_NEW_SUPPLIER, EPosWidgetNewSupplierClass))
#define EPOS_IS_WIDGET_NEW_SUPPLIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_NEW_SUPPLIER))
#define EPOS_IS_WIDGET_NEW_SUPPLIER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_NEW_SUPPLIER))
#define EPOS_WIDGET_NEW_SUPPLIER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_NEW_SUPPLIER, EPosWidgetNewSupplierClass))

typedef struct _EPosWidgetNewSupplier EPosWidgetNewSupplier;
typedef struct _EPosWidgetNewSupplierClass EPosWidgetNewSupplierClass;
typedef struct _EPosWidgetNewSupplierPrivate EPosWidgetNewSupplierPrivate;

#define EPOS_TYPE_WIDGET_PRODUCT_LINES (epos_widget_product_lines_get_type ())
#define EPOS_WIDGET_PRODUCT_LINES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_PRODUCT_LINES, EPosWidgetProductLines))
#define EPOS_WIDGET_PRODUCT_LINES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_PRODUCT_LINES, EPosWidgetProductLinesClass))
#define EPOS_IS_WIDGET_PRODUCT_LINES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_PRODUCT_LINES))
#define EPOS_IS_WIDGET_PRODUCT_LINES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_PRODUCT_LINES))
#define EPOS_WIDGET_PRODUCT_LINES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_PRODUCT_LINES, EPosWidgetProductLinesClass))

typedef struct _EPosWidgetProductLines EPosWidgetProductLines;
typedef struct _EPosWidgetProductLinesClass EPosWidgetProductLinesClass;
typedef struct _EPosWidgetProductLinesPrivate EPosWidgetProductLinesPrivate;

#define EPOS_TYPE_WIDGET_PRODUCTS_SEARCH (epos_widget_products_search_get_type ())
#define EPOS_WIDGET_PRODUCTS_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_PRODUCTS_SEARCH, EPosWidgetProductsSearch))
#define EPOS_WIDGET_PRODUCTS_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_PRODUCTS_SEARCH, EPosWidgetProductsSearchClass))
#define EPOS_IS_WIDGET_PRODUCTS_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_PRODUCTS_SEARCH))
#define EPOS_IS_WIDGET_PRODUCTS_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_PRODUCTS_SEARCH))
#define EPOS_WIDGET_PRODUCTS_SEARCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_PRODUCTS_SEARCH, EPosWidgetProductsSearchClass))

typedef struct _EPosWidgetProductsSearch EPosWidgetProductsSearch;
typedef struct _EPosWidgetProductsSearchClass EPosWidgetProductsSearchClass;
typedef struct _EPosWidgetProductsSearchPrivate EPosWidgetProductsSearchPrivate;

#define EPOS_WIDGET_PRODUCTS_SEARCH_TYPE_COLUMNS (epos_widget_products_search_columns_get_type ())

#define EPOS_TYPE_WIDGET_PURCHASE_ORDER (epos_widget_purchase_order_get_type ())
#define EPOS_WIDGET_PURCHASE_ORDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_PURCHASE_ORDER, EPosWidgetPurchaseOrder))
#define EPOS_WIDGET_PURCHASE_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_PURCHASE_ORDER, EPosWidgetPurchaseOrderClass))
#define EPOS_IS_WIDGET_PURCHASE_ORDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_PURCHASE_ORDER))
#define EPOS_IS_WIDGET_PURCHASE_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_PURCHASE_ORDER))
#define EPOS_WIDGET_PURCHASE_ORDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_PURCHASE_ORDER, EPosWidgetPurchaseOrderClass))

typedef struct _EPosWidgetPurchaseOrder EPosWidgetPurchaseOrder;
typedef struct _EPosWidgetPurchaseOrderClass EPosWidgetPurchaseOrderClass;
typedef struct _EPosWidgetPurchaseOrderPrivate EPosWidgetPurchaseOrderPrivate;

#define EPOS_WIDGET_PURCHASE_ORDER_TYPE_COLUMNS (epos_widget_purchase_order_columns_get_type ())

#define EPOS_TYPE_WIDGET_PURCHASE_ORDERS (epos_widget_purchase_orders_get_type ())
#define EPOS_WIDGET_PURCHASE_ORDERS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_PURCHASE_ORDERS, EPosWidgetPurchaseOrders))
#define EPOS_WIDGET_PURCHASE_ORDERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_PURCHASE_ORDERS, EPosWidgetPurchaseOrdersClass))
#define EPOS_IS_WIDGET_PURCHASE_ORDERS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_PURCHASE_ORDERS))
#define EPOS_IS_WIDGET_PURCHASE_ORDERS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_PURCHASE_ORDERS))
#define EPOS_WIDGET_PURCHASE_ORDERS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_PURCHASE_ORDERS, EPosWidgetPurchaseOrdersClass))

typedef struct _EPosWidgetPurchaseOrders EPosWidgetPurchaseOrders;
typedef struct _EPosWidgetPurchaseOrdersClass EPosWidgetPurchaseOrdersClass;
typedef struct _EPosWidgetPurchaseOrdersPrivate EPosWidgetPurchaseOrdersPrivate;

#define EPOS_WIDGET_PURCHASE_ORDERS_TYPE_COLUMNS (epos_widget_purchase_orders_columns_get_type ())

#define EPOS_TYPE_WIDGET_RECEIVE_PURCHASE_ORDER (epos_widget_receive_purchase_order_get_type ())
#define EPOS_WIDGET_RECEIVE_PURCHASE_ORDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_RECEIVE_PURCHASE_ORDER, EPosWidgetReceivePurchaseOrder))
#define EPOS_WIDGET_RECEIVE_PURCHASE_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_RECEIVE_PURCHASE_ORDER, EPosWidgetReceivePurchaseOrderClass))
#define EPOS_IS_WIDGET_RECEIVE_PURCHASE_ORDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_RECEIVE_PURCHASE_ORDER))
#define EPOS_IS_WIDGET_RECEIVE_PURCHASE_ORDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_RECEIVE_PURCHASE_ORDER))
#define EPOS_WIDGET_RECEIVE_PURCHASE_ORDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_RECEIVE_PURCHASE_ORDER, EPosWidgetReceivePurchaseOrderClass))

typedef struct _EPosWidgetReceivePurchaseOrder EPosWidgetReceivePurchaseOrder;
typedef struct _EPosWidgetReceivePurchaseOrderClass EPosWidgetReceivePurchaseOrderClass;
typedef struct _EPosWidgetReceivePurchaseOrderPrivate EPosWidgetReceivePurchaseOrderPrivate;

#define EPOS_TYPE_WIDGET_STOCK_TRANSFERS (epos_widget_stock_transfers_get_type ())
#define EPOS_WIDGET_STOCK_TRANSFERS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_STOCK_TRANSFERS, EPosWidgetStockTransfers))
#define EPOS_WIDGET_STOCK_TRANSFERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_STOCK_TRANSFERS, EPosWidgetStockTransfersClass))
#define EPOS_IS_WIDGET_STOCK_TRANSFERS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_STOCK_TRANSFERS))
#define EPOS_IS_WIDGET_STOCK_TRANSFERS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_STOCK_TRANSFERS))
#define EPOS_WIDGET_STOCK_TRANSFERS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_STOCK_TRANSFERS, EPosWidgetStockTransfersClass))

typedef struct _EPosWidgetStockTransfers EPosWidgetStockTransfers;
typedef struct _EPosWidgetStockTransfersClass EPosWidgetStockTransfersClass;
typedef struct _EPosWidgetStockTransfersPrivate EPosWidgetStockTransfersPrivate;

#define EPOS_TYPE_WIDGET_SUPPLIER_CATEGORIES (epos_widget_supplier_categories_get_type ())
#define EPOS_WIDGET_SUPPLIER_CATEGORIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_SUPPLIER_CATEGORIES, EPosWidgetSupplierCategories))
#define EPOS_WIDGET_SUPPLIER_CATEGORIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_SUPPLIER_CATEGORIES, EPosWidgetSupplierCategoriesClass))
#define EPOS_IS_WIDGET_SUPPLIER_CATEGORIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_SUPPLIER_CATEGORIES))
#define EPOS_IS_WIDGET_SUPPLIER_CATEGORIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_SUPPLIER_CATEGORIES))
#define EPOS_WIDGET_SUPPLIER_CATEGORIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_SUPPLIER_CATEGORIES, EPosWidgetSupplierCategoriesClass))

typedef struct _EPosWidgetSupplierCategories EPosWidgetSupplierCategories;
typedef struct _EPosWidgetSupplierCategoriesClass EPosWidgetSupplierCategoriesClass;
typedef struct _EPosWidgetSupplierCategoriesPrivate EPosWidgetSupplierCategoriesPrivate;

#define EPOS_WIDGET_SUPPLIER_CATEGORIES_TYPE_COLUMNS (epos_widget_supplier_categories_columns_get_type ())

#define EPOS_TYPE_WIDGET_SUPPLIERS (epos_widget_suppliers_get_type ())
#define EPOS_WIDGET_SUPPLIERS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_SUPPLIERS, EPosWidgetSuppliers))
#define EPOS_WIDGET_SUPPLIERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_SUPPLIERS, EPosWidgetSuppliersClass))
#define EPOS_IS_WIDGET_SUPPLIERS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_SUPPLIERS))
#define EPOS_IS_WIDGET_SUPPLIERS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_SUPPLIERS))
#define EPOS_WIDGET_SUPPLIERS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_SUPPLIERS, EPosWidgetSuppliersClass))

typedef struct _EPosWidgetSuppliers EPosWidgetSuppliers;
typedef struct _EPosWidgetSuppliersClass EPosWidgetSuppliersClass;
typedef struct _EPosWidgetSuppliersPrivate EPosWidgetSuppliersPrivate;

#define EPOS_WIDGET_SUPPLIERS_TYPE_COLUMNS (epos_widget_suppliers_columns_get_type ())

#define EPOS_TYPE_WIDGET_TRANSACTION_TYPES (epos_widget_transaction_types_get_type ())
#define EPOS_WIDGET_TRANSACTION_TYPES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_TRANSACTION_TYPES, EPosWidgetTransactionTypes))
#define EPOS_WIDGET_TRANSACTION_TYPES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_TRANSACTION_TYPES, EPosWidgetTransactionTypesClass))
#define EPOS_IS_WIDGET_TRANSACTION_TYPES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_TRANSACTION_TYPES))
#define EPOS_IS_WIDGET_TRANSACTION_TYPES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_TRANSACTION_TYPES))
#define EPOS_WIDGET_TRANSACTION_TYPES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_TRANSACTION_TYPES, EPosWidgetTransactionTypesClass))

typedef struct _EPosWidgetTransactionTypes EPosWidgetTransactionTypes;
typedef struct _EPosWidgetTransactionTypesClass EPosWidgetTransactionTypesClass;
typedef struct _EPosWidgetTransactionTypesPrivate EPosWidgetTransactionTypesPrivate;

#define EPOS_TYPE_WIDGET_TRANSACTIONS (epos_widget_transactions_get_type ())
#define EPOS_WIDGET_TRANSACTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_TRANSACTIONS, EPosWidgetTransactions))
#define EPOS_WIDGET_TRANSACTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_TRANSACTIONS, EPosWidgetTransactionsClass))
#define EPOS_IS_WIDGET_TRANSACTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_TRANSACTIONS))
#define EPOS_IS_WIDGET_TRANSACTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_TRANSACTIONS))
#define EPOS_WIDGET_TRANSACTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_TRANSACTIONS, EPosWidgetTransactionsClass))

typedef struct _EPosWidgetTransactions EPosWidgetTransactions;
typedef struct _EPosWidgetTransactionsClass EPosWidgetTransactionsClass;
typedef struct _EPosWidgetTransactionsPrivate EPosWidgetTransactionsPrivate;

#define EPOS_WIDGET_TRANSACTIONS_TYPE_COLUMNS (epos_widget_transactions_columns_get_type ())

#define EPOS_TYPE_WIDGET_UNIT_OF_MEASUREMENT (epos_widget_unit_of_measurement_get_type ())
#define EPOS_WIDGET_UNIT_OF_MEASUREMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_UNIT_OF_MEASUREMENT, EPosWidgetUnitOfMeasurement))
#define EPOS_WIDGET_UNIT_OF_MEASUREMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_UNIT_OF_MEASUREMENT, EPosWidgetUnitOfMeasurementClass))
#define EPOS_IS_WIDGET_UNIT_OF_MEASUREMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_UNIT_OF_MEASUREMENT))
#define EPOS_IS_WIDGET_UNIT_OF_MEASUREMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_UNIT_OF_MEASUREMENT))
#define EPOS_WIDGET_UNIT_OF_MEASUREMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_UNIT_OF_MEASUREMENT, EPosWidgetUnitOfMeasurementClass))

typedef struct _EPosWidgetUnitOfMeasurement EPosWidgetUnitOfMeasurement;
typedef struct _EPosWidgetUnitOfMeasurementClass EPosWidgetUnitOfMeasurementClass;
typedef struct _EPosWidgetUnitOfMeasurementPrivate EPosWidgetUnitOfMeasurementPrivate;

#define EPOS_TYPE_WIDGET_VIEW_TRANSACTION (epos_widget_view_transaction_get_type ())
#define EPOS_WIDGET_VIEW_TRANSACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_WIDGET_VIEW_TRANSACTION, EPosWidgetViewTransaction))
#define EPOS_WIDGET_VIEW_TRANSACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_WIDGET_VIEW_TRANSACTION, EPosWidgetViewTransactionClass))
#define EPOS_IS_WIDGET_VIEW_TRANSACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_WIDGET_VIEW_TRANSACTION))
#define EPOS_IS_WIDGET_VIEW_TRANSACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_WIDGET_VIEW_TRANSACTION))
#define EPOS_WIDGET_VIEW_TRANSACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_WIDGET_VIEW_TRANSACTION, EPosWidgetViewTransactionClass))

typedef struct _EPosWidgetViewTransaction EPosWidgetViewTransaction;
typedef struct _EPosWidgetViewTransactionClass EPosWidgetViewTransactionClass;
typedef struct _EPosWidgetViewTransactionPrivate EPosWidgetViewTransactionPrivate;

#define EPOS_WIDGET_VIEW_TRANSACTION_TYPE_COLUMNS (epos_widget_view_transaction_columns_get_type ())

#define EPOS_TYPE_DIALOG_NEW_ADJUSTMENT (epos_dialog_new_adjustment_get_type ())
#define EPOS_DIALOG_NEW_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_DIALOG_NEW_ADJUSTMENT, EPosDialogNewAdjustment))
#define EPOS_DIALOG_NEW_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_DIALOG_NEW_ADJUSTMENT, EPosDialogNewAdjustmentClass))
#define EPOS_IS_DIALOG_NEW_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_DIALOG_NEW_ADJUSTMENT))
#define EPOS_IS_DIALOG_NEW_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_DIALOG_NEW_ADJUSTMENT))
#define EPOS_DIALOG_NEW_ADJUSTMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_DIALOG_NEW_ADJUSTMENT, EPosDialogNewAdjustmentClass))

typedef struct _EPosDialogNewAdjustment EPosDialogNewAdjustment;
typedef struct _EPosDialogNewAdjustmentClass EPosDialogNewAdjustmentClass;
typedef struct _EPosDialogNewAdjustmentPrivate EPosDialogNewAdjustmentPrivate;

#define EPOS_TYPE_INVENTORY_HELPER (epos_inventory_helper_get_type ())
#define EPOS_INVENTORY_HELPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_TYPE_INVENTORY_HELPER, EPosInventoryHelper))
#define EPOS_INVENTORY_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_TYPE_INVENTORY_HELPER, EPosInventoryHelperClass))
#define EPOS_IS_INVENTORY_HELPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_TYPE_INVENTORY_HELPER))
#define EPOS_IS_INVENTORY_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_TYPE_INVENTORY_HELPER))
#define EPOS_INVENTORY_HELPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_TYPE_INVENTORY_HELPER, EPosInventoryHelperClass))

typedef struct _EPosInventoryHelper EPosInventoryHelper;
typedef struct _EPosInventoryHelperClass EPosInventoryHelperClass;
typedef struct _EPosInventoryHelperPrivate EPosInventoryHelperPrivate;

struct _EPosSB_ModuleInventory {
	SinticBoliviaGtkSBGtkModule parent_instance;
	EPosSB_ModuleInventoryPrivate * priv;
};

struct _EPosSB_ModuleInventoryClass {
	SinticBoliviaGtkSBGtkModuleClass parent_class;
};

struct _EPosEAssemblyComponent {
	GObject parent_instance;
	EPosEAssemblyComponentPrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
	EPosEProduct* Product;
};

struct _EPosEAssemblyComponentClass {
	GObjectClass parent_class;
};

struct _EPosEAssembly {
	GObject parent_instance;
	EPosEAssemblyPrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
	GeeArrayList* components;
};

struct _EPosEAssemblyClass {
	GObjectClass parent_class;
};

struct _EPosCatalog {
	GObject parent_instance;
	EPosCatalogPrivate * priv;
	gchar* Title;
	gfloat XPos;
	gfloat YPos;
	gchar* FontType;
	gfloat FontSize;
	gfloat* ColumnsWidth;
	gint ColumnsWidth_length1;
	gfloat TopMargin;
	gfloat RightMargin;
	gfloat BottomMargin;
	gfloat LeftMargin;
	HPDF_Doc* pdf;
	HPDF_Page* page;
	HPDF_Font* font;
	gfloat pageWidth;
	gfloat pageHeight;
	gfloat pageAvailableSpace;
	gint totalCols;
	gfloat rowHeight;
};

struct _EPosCatalogClass {
	GObjectClass parent_class;
};

struct _EPosOrder {
	GObject parent_instance;
	EPosOrderPrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
	GeeArrayList* items;
	SinticBoliviaSBUser* User;
};

struct _EPosOrderClass {
	GObjectClass parent_class;
};

struct _EPosPdfCell {
	GObject parent_instance;
	EPosPdfCellPrivate * priv;
	HPDF_Font* Font;
	gchar* text;
	HPDF_Image* image;
	EPosPdfRow* Row;
	gint Index;
	gfloat Width;
	gfloat Height;
	gfloat SourceX;
	gfloat SourceY;
	gchar* FontFamily;
	gfloat FontSize;
	gint Span;
	gboolean TopBorder;
	gboolean RightBorder;
	gboolean BottomBorder;
	gboolean LeftBorder;
	gfloat Padding;
	gchar* Align;
	GeeArrayList* lines;
};

struct _EPosPdfCellClass {
	GObjectClass parent_class;
};

struct _EPosPdfRow {
	GObject parent_instance;
	EPosPdfRowPrivate * priv;
	GeeArrayList* cells;
	EPosPdfTable* Table;
	gfloat Width;
	gfloat Height;
	gfloat X;
	gfloat Y;
	gfloat SourceX;
	gfloat SourceY;
	gint NumCells;
	gfloat* ColumnsWidth;
	gint ColumnsWidth_length1;
};

struct _EPosPdfRowClass {
	GObjectClass parent_class;
};

struct _EPosPdfTable {
	GObject parent_instance;
	EPosPdfTablePrivate * priv;
	GeeArrayList* rows;
	HPDF_Page* PdfPage;
	HPDF_Doc* Doc;
	HPDF_Font* Font;
	gint totalCols;
	gfloat Width;
	gfloat Height;
	gfloat X;
	gfloat Y;
	gfloat SourceX;
	gfloat SourceY;
	gfloat* ColumnsWidth;
	gint ColumnsWidth_length1;
	gchar** Headers;
	gint Headers_length1;
	EPosPdfRow* currentRow;
	gint currentCell;
};

struct _EPosPdfTableClass {
	GObjectClass parent_class;
};

struct _EPosEProduct {
	GObject parent_instance;
	EPosEProductPrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
	GeeArrayList* images;
	GeeArrayList* Attachments;
	GeeArrayList* categoriesIds;
	GeeArrayList* categories;
};

struct _EPosEProductClass {
	GObjectClass parent_class;
};

struct _EPosEPurchaseOrderItem {
	GObject parent_instance;
	EPosEPurchaseOrderItemPrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
};

struct _EPosEPurchaseOrderItemClass {
	GObjectClass parent_class;
};

struct _EPosPurchaseOrder {
	EPosOrder parent_instance;
	EPosPurchaseOrderPrivate * priv;
};

struct _EPosPurchaseOrderClass {
	EPosOrderClass parent_class;
};

struct _WoocommerceSale {
	GObject parent_instance;
	WoocommerceSalePrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
};

struct _WoocommerceSaleClass {
	GObjectClass parent_class;
};

struct _EPosESupplier {
	GObject parent_instance;
	EPosESupplierPrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
};

struct _EPosESupplierClass {
	GObjectClass parent_class;
};

struct _EPosETaxRate {
	GObject parent_instance;
	EPosETaxRatePrivate * priv;
	SinticBoliviaDatabaseSBDBRow* dbData;
};

struct _EPosETaxRateClass {
	GObjectClass parent_class;
};

struct _WoocommerceInvoiceTicketInvoice {
	GObject parent_instance;
	WoocommerceInvoiceTicketInvoicePrivate * priv;
	cairo_t* ctx;
	gint width;
	gint height;
	gint innerWidth;
	gchar* body;
	gdouble fontSize;
	gint pageMargin;
	gint padding;
};

struct _WoocommerceInvoiceTicketInvoiceClass {
	GObjectClass parent_class;
};

struct _EPosWidgetItemTypes {
	GtkBox parent_instance;
	EPosWidgetItemTypesPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxItemTypes;
	GtkImage* image1;
	GtkButton* buttonAdd;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkScrolledWindow* scrolledwindow1;
	SinticBoliviaGtkDbTableTreeView* treeview;
	GtkDialog* dlg;
	GtkEntry* entryCode;
	GtkEntry* entryName;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint itemTypeId;
};

struct _EPosWidgetItemTypesClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetAdjustments {
	GtkBox parent_instance;
	EPosWidgetAdjustmentsPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkImage* image1;
	GtkButton* buttonNew;
	GtkButton* buttonCancel;
	GtkComboBox* comboboxStore;
	GtkTreeView* treeviewItems;
};

struct _EPosWidgetAdjustmentsClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_COUNT,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_SELECT,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_CODE,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_STATUS,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_STORE,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_NOTE,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_PRODUCT,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_OLD_QTY,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_NEW_QTY,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_ID,
	EPOS_WIDGET_ADJUSTMENTS_COLUMNS_N_COLS
} EPosWidgetAdjustmentsColumns;

struct _EPosWidgetAssemblies {
	GtkBox parent_instance;
	EPosWidgetAssembliesPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxAssemblies;
	GtkImage* image1;
	GtkButton* buttonAdd;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkComboBox* comboboxStore;
	GtkTreeView* treeviewAssemblies;
};

struct _EPosWidgetAssembliesClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetCurrencies {
	GtkBox parent_instance;
	EPosWidgetCurrenciesPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxCurrencies;
	GtkImage* image1;
	GtkButton* buttonAdd;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkScrolledWindow* scrolledwindow1;
	SinticBoliviaGtkDbTableTreeView* treeview;
	GtkDialog* dlg;
	GtkEntry* entryCode;
	GtkEntry* entryName;
	GtkEntry* entryRate;
	GtkButton* buttonSave;
	GtkButton* buttonCancel;
	gint currencyId;
};

struct _EPosWidgetCurrenciesClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetProductDepartments {
	GtkBox parent_instance;
	EPosWidgetProductDepartmentsPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxDepartments;
	GtkImage* image1;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkScrolledWindow* scrolledwindow1;
	SinticBoliviaGtkDbTableTreeView* treeview;
	GtkDialog* dlg;
	GtkEntry* entryName;
	GtkEntry* entryDescription;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint depId;
};

struct _EPosWidgetProductDepartmentsClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetInventory {
	GtkBox parent_instance;
	EPosWidgetInventoryPrivate * priv;
	GtkBuilder* ui;
	GtkWindow* windowProducts;
	GtkBox* boxProducts;
	GtkImage* imageStores;
	GtkLabel* labelStoresTitle;
	GtkPaned* panedBranches;
	GtkButton* buttonAddStore;
	GtkButton* buttonEditStore;
	GtkButton* buttonDeleteStore;
	GtkEntry* entrySearchStore;
	GtkTreeView* treeviewStores;
	GtkBox* boxStore;
	GtkEntry* entryStoreName;
	GtkEntry* entryStoreAddress;
	GtkComboBox* comboboxTax;
	GtkComboBox* comboboxSalesDocument;
	GtkComboBox* comboboxPurchaseDocument;
	GtkComboBox* comboboxRefundDocument;
	GtkComboBox* comboboxAdjustmentDoc;
	GtkButton* buttonSaveStore;
	GtkButton* buttonCancelStore;
	GtkPaned* panedCategories;
	GtkImage* imageCategories;
	GtkButton* buttonNewCategory;
	GtkButton* buttonEditCategory;
	GtkButton* buttonDeleteCategory;
	GtkTreeView* treeviewCategories;
	GtkComboBox* comboboxCategoriesStore;
	GtkEntry* entryCategoryName;
	GtkTextView* textviewCategoryDescription;
	GtkComboBox* comboboxParentCategory;
	GtkComboBox* comboboxCategoryStore;
	GtkButton* buttonSaveCategory;
	GtkButton* buttonCancelCategory;
	GtkImage* imageProducts;
	GtkButtonBox* buttonboxProducts;
	GtkButton* buttonNewProduct;
	GtkButton* buttonEditProduct;
	GtkButton* buttonDeleteProduct;
	GtkComboBox* comboboxStore;
	GtkComboBox* comboboxCategory;
	GtkButton* buttonRefreshProducts;
	GtkEntry* entrySearchProduct;
	GtkComboBox* comboboxProductSearchBy;
	GtkTreeView* treeviewProducts;
	GtkButton* buttonFirst;
	GtkButton* buttonPrev;
	GtkButton* buttonNext;
	GtkButton* buttonLast;
	GtkLabel* labelTotalProducts;
	GtkLabel* labelViewProducts;
	GtkLabel* labelViewTotal;
	gboolean lockCategoryEvent;
	gint _category_id;
	gint _store_id;
	gint _product_id;
};

struct _EPosWidgetInventoryClass {
	GtkBoxClass parent_class;
};

struct _EPosWindowNewAssembly {
	GtkWindow parent_instance;
	EPosWindowNewAssemblyPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxNewAssembly;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkEntry* entryName;
	GtkTextView* textviewDescription;
	GtkTreeView* treeview1;
	GtkEntry* entrySearchProduct;
	GtkEntry* entryRequiredQty;
	GtkComboBox* comboboxUOM;
	GtkButton* buttonAdd;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint AssemblyId;
};

struct _EPosWindowNewAssemblyClass {
	GtkWindowClass parent_class;
};

struct _EPosWidgetNewProduct {
	GtkBox parent_instance;
	EPosWidgetNewProductPrivate * priv;
	GtkBuilder* ui;
	GtkWindow* windowNewProduct;
	GtkBox* boxNewProduct;
	GtkNotebook* notebook1;
	GtkComboBox* comboboxCategories;
	GtkComboBox* comboboxDepartment;
	GtkTextView* textviewDescription;
	GtkEntry* entryCode;
	GtkButton* buttonGenerateCode;
	GtkEntry* entryName;
	GtkEntry* entryBarcode;
	GtkComboBox* comboboxItemType;
	GtkComboBox* comboboxUnitofMeasure;
	GtkComboBox* comboboxStatus;
	GtkComboBox* comboboxTaxRates;
	GtkEntry* entryCost;
	GtkEntry* entryPrice;
	GtkEntry* entryPrice2;
	GtkComboBox* comboboxStoreBranch;
	GtkEntry* entryQuantity;
	GtkEntry* entryMinQuantity;
	GtkCheckButton* checkbuttonUsesStock;
	GtkViewport* viewport1;
	GtkFixed* fixedImages;
	GtkScrolledWindow* scrolledwindowSn;
	GtkEntry* entrySn;
	GtkTreeView* treeviewSn;
	GtkTreeView* treeviewSuppliers;
	GtkEntry* entrySearchSupplier;
	GtkButton* buttonAddSupplier;
	GtkButton* buttonAddSn;
	GtkButton* buttonRemoveSn;
	GtkButton* buttonAddImage;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	EPosEProduct* product;
	gint fixedWidth;
	gint fixedX;
	gint fixedY;
	gint fixedRow;
	gint fixedCol;
};

struct _EPosWidgetNewProductClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetNewSupplier {
	GtkBox parent_instance;
	EPosWidgetNewSupplierPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxSupplier;
	GtkImage* image1;
	GtkLabel* labelDetailsTitle;
	GtkViewport* viewportDetailsBody;
	GtkEntry* entrySupplierName;
	GtkEntry* entryDefaultMarkup;
	GtkTextView* textviewDescription;
	GtkEntry* entryCompany;
	GtkEntry* entryContactFirstName;
	GtkEntry* entryPhone;
	GtkEntry* entryMobile;
	GtkEntry* entryEmail;
	GtkEntry* entryWebsite;
	GtkEntry* entryStreet;
	GtkEntry* entryCity;
	GtkComboBox* comboboxCountry;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint supplierId;
};

struct _EPosWidgetNewSupplierClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetProductLines {
	GtkBox parent_instance;
	EPosWidgetProductLinesPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkImage* image1;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkScrolledWindow* scrolledwindow1;
	SinticBoliviaGtkDbTableTreeView* tv;
	GtkDialog* dlg;
	GtkEntry* entryName;
	GtkEntry* entryDescription;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint lineId;
};

struct _EPosWidgetProductLinesClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetProductsSearch {
	GtkBox parent_instance;
	EPosWidgetProductsSearchPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkEntry* entrySearch;
	GtkComboBox* comboboxSearchBy;
	GtkTreeView* treeviewProducts;
	gint storeId;
};

struct _EPosWidgetProductsSearchClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_PRODUCTS_SEARCH_COLUMNS_COUNT,
	EPOS_WIDGET_PRODUCTS_SEARCH_COLUMNS_ID,
	EPOS_WIDGET_PRODUCTS_SEARCH_COLUMNS_NAME,
	EPOS_WIDGET_PRODUCTS_SEARCH_COLUMNS_QUANTITY,
	EPOS_WIDGET_PRODUCTS_SEARCH_COLUMNS_PRICE,
	EPOS_WIDGET_PRODUCTS_SEARCH_COLUMNS_N_COLS
} EPosWidgetProductsSearchColumns;

struct _EPosWidgetPurchaseOrder {
	GtkBox parent_instance;
	EPosWidgetPurchaseOrderPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxPurchaseOrder;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkComboBox* comboboxStores;
	SinticBoliviaGtkSBDatePicker* datepickerOrderDate;
	SinticBoliviaGtkSBDatePicker* datepickerDeliveryDate;
	GtkComboBox* comboboxSuppliers;
	GtkEntry* entryDetails;
	GtkEntry* entrySearchProduct;
	GtkSpinButton* spinbuttonProductQty;
	GtkComboBox* comboboxSearchType;
	GtkButton* buttonAddProduct;
	GtkTreeView* treeviewProducts;
	GtkButtonBox* buttonbox1;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	GtkLabel* labelSubTotal;
	GtkLabel* labelTotalTax;
	GtkLabel* labelTotal;
	gint total_items;
	EPosPurchaseOrder* order;
};

struct _EPosWidgetPurchaseOrderClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_COUNT,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_PRODUCT_NAME,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_CURRENT_QTY,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_QTY,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_COST,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_SUB_TOTAL,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_TAX,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_TOTAL,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_IMAGE,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_PRODUCT_ID,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_TAX_RATE,
	EPOS_WIDGET_PURCHASE_ORDER_COLUMNS_N
} EPosWidgetPurchaseOrderColumns;

struct _EPosWidgetPurchaseOrders {
	GtkBox parent_instance;
	EPosWidgetPurchaseOrdersPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxPurchaseOrders;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonReceive;
	GtkButton* buttonCancel;
	GtkButton* buttonPrint;
	GtkButton* buttonPreview;
	GtkComboBox* comboboxStores;
	GtkComboBox* comboboxStatus;
	GtkTreeView* treeviewOrders;
};

struct _EPosWidgetPurchaseOrdersClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_COUNT,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_STORE,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_ITEMS,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_TOTAL,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_DELIVERY_DATE,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_STATUS,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_CREATION_DATE,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_ORDER_ID,
	EPOS_WIDGET_PURCHASE_ORDERS_COLUMNS_N_COLS
} EPosWidgetPurchaseOrdersColumns;

struct _EPosWidgetReceivePurchaseOrder {
	GtkBox parent_instance;
	EPosWidgetReceivePurchaseOrderPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxReceivePurchaseOrder;
	GtkImage* image1;
	GtkLabel* labelPurchaseOrderCode;
	GtkLabel* labelOrderDate;
	GtkLabel* labelReceiverStore;
	GtkLabel* labelSupplierName;
	GtkTreeView* treeviewOrderItems;
	GtkLabel* labelProductTaxRate;
	GtkLabel* labelSubTotal;
	GtkLabel* labelTotalTax;
	GtkLabel* labelTotalDiscount;
	GtkLabel* labelTotal;
	GtkButton* buttonCancel;
	GtkButton* buttonReceive;
	EPosPurchaseOrder* order;
};

struct _EPosWidgetReceivePurchaseOrderClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetStockTransfers {
	GtkBox parent_instance;
	EPosWidgetStockTransfersPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxStockTransfer;
	GtkImage* image1;
	GtkButton* buttonRequest;
	GtkButton* buttonReceive;
	GtkTreeView* treeviewTransfers;
};

struct _EPosWidgetStockTransfersClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetSupplierCategories {
	GtkBox parent_instance;
	EPosWidgetSupplierCategoriesPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkImage* image1;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkTreeView* treeviewCategories;
	GtkWindow* windowNewCategory;
	GtkEntry* entryCategoryName;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint categoryId;
};

struct _EPosWidgetSupplierCategoriesClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_SUPPLIER_CATEGORIES_COLUMNS_COUNT,
	EPOS_WIDGET_SUPPLIER_CATEGORIES_COLUMNS_ID,
	EPOS_WIDGET_SUPPLIER_CATEGORIES_COLUMNS_NAME,
	EPOS_WIDGET_SUPPLIER_CATEGORIES_COLUMNS_ITEMS,
	EPOS_WIDGET_SUPPLIER_CATEGORIES_COLUMNS_N_COLS
} EPosWidgetSupplierCategoriesColumns;

struct _EPosWidgetSuppliers {
	GtkBox parent_instance;
	EPosWidgetSuppliersPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxSuppliers;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkComboBox* comboboxStore;
	GtkTreeView* treeviewSuppliers;
};

struct _EPosWidgetSuppliersClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_SUPPLIERS_COLUMNS_COUNT,
	EPOS_WIDGET_SUPPLIERS_COLUMNS_SUPPLIER_NAME,
	EPOS_WIDGET_SUPPLIERS_COLUMNS_COMPANY,
	EPOS_WIDGET_SUPPLIERS_COLUMNS_CITY,
	EPOS_WIDGET_SUPPLIERS_COLUMNS_MARKUP,
	EPOS_WIDGET_SUPPLIERS_COLUMNS_SUPPLIER_ID,
	EPOS_WIDGET_SUPPLIERS_COLUMNS_N_COLS
} EPosWidgetSuppliersColumns;

struct _EPosWidgetTransactionTypes {
	GtkBox parent_instance;
	EPosWidgetTransactionTypesPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxTransactionTypes;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkTreeView* treeview1;
	GtkDialog* dlg;
	GtkEntry* entryKey;
	GtkEntry* entryName;
	GtkComboBox* comboboxType;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint ttId;
};

struct _EPosWidgetTransactionTypesClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetTransactions {
	GtkBox parent_instance;
	EPosWidgetTransactionsPrivate * priv;
	GtkBuilder* ui;
	GtkWindow* windowTransactions;
	GtkBox* boxTransactions;
	GtkImage* image1;
	GtkBox* boxButtons;
	GtkButton* buttonView;
	GtkButton* buttonEdit;
	GtkButton* buttonRevert;
	GtkButton* buttonDelete;
	GtkBox* boxFilters;
	GtkComboBox* comboboxStore;
	GtkComboBox* comboboxTransactionType;
	GtkTreeView* treeviewTransactions;
	SinticBoliviaSBStore* store;
};

struct _EPosWidgetTransactionsClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_CHECKBOX,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_ID,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_STORE,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_TYPE,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_TOTAL,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_NUM_ITEMS,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_STATUS,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_USER_ID,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_DATETIME,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_G_TYPE,
	EPOS_WIDGET_TRANSACTIONS_COLUMNS_N_COLS
} EPosWidgetTransactionsColumns;

struct _EPosWidgetUnitOfMeasurement {
	GtkBox parent_instance;
	EPosWidgetUnitOfMeasurementPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxUm;
	GtkImage* image1;
	GtkButton* buttonNew;
	GtkButton* buttonEdit;
	GtkButton* buttonDelete;
	GtkTreeView* treeview1;
	GtkDialog* dlg;
	GtkEntry* entryCode;
	GtkEntry* entryName;
	GtkEntry* entryQty;
	GtkButton* buttonSave;
	GtkButton* buttonCancel;
	gint theId;
};

struct _EPosWidgetUnitOfMeasurementClass {
	GtkBoxClass parent_class;
};

struct _EPosWidgetViewTransaction {
	GtkBox parent_instance;
	EPosWidgetViewTransactionPrivate * priv;
	GtkBuilder* ui;
	GtkBox* boxViewTransaction;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkTreeView* treeviewItems;
	GtkLabel* labelSubtotal;
	GtkLabel* labelDiscount;
	GtkLabel* labelTotal;
	GtkButton* buttonClose;
	GtkButton* buttonPrint;
	GtkButton* buttonRefund;
	GObject* transaction;
	gint transactionId;
};

struct _EPosWidgetViewTransactionClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WIDGET_VIEW_TRANSACTION_COLUMNS_COUNT,
	EPOS_WIDGET_VIEW_TRANSACTION_COLUMNS_ITEM,
	EPOS_WIDGET_VIEW_TRANSACTION_COLUMNS_QTY,
	EPOS_WIDGET_VIEW_TRANSACTION_COLUMNS_PRICE,
	EPOS_WIDGET_VIEW_TRANSACTION_COLUMNS_TOTAL,
	EPOS_WIDGET_VIEW_TRANSACTION_COLUMNS_N_COLS
} EPosWidgetViewTransactionColumns;

struct _EPosDialogNewAdjustment {
	GtkDialog parent_instance;
	EPosDialogNewAdjustmentPrivate * priv;
	GtkImage* image1;
	GtkLabel* labelTitle;
	GtkGrid* grid1;
	GtkComboBox* comboboxStore;
	GtkLabel* labelDate;
	SinticBoliviaGtkSBDatePicker* datepicker;
	GtkEntry* entrySearch;
	GtkEntry* entryQty;
	GtkTextView* textviewNotes;
	GtkButton* buttonCancel;
	GtkButton* buttonSave;
	gint storeId;
	gint productId;
};

struct _EPosDialogNewAdjustmentClass {
	GtkDialogClass parent_class;
};

struct _EPosInventoryHelper {
	GObject parent_instance;
	EPosInventoryHelperPrivate * priv;
};

struct _EPosInventoryHelperClass {
	GObjectClass parent_class;
};


GType epos_sb_moduleinventory_get_type (void) G_GNUC_CONST;
void epos_sb_moduleinventory_ApplyPatches (EPosSB_ModuleInventory* self);
void epos_sb_moduleinventory_sidebar_init (SinticBoliviaSBModuleArgs* harg);
void epos_sb_moduleinventory_init_menu_management (SinticBoliviaSBModuleArgs* args);
void epos_sb_moduleinventory_hook_reports_menu (SinticBoliviaSBModuleArgs* args);
void epos_sb_moduleinventory_hook_user_fields (SinticBoliviaSBModuleArgs* args);
void epos_sb_moduleinventory_hook_user_saved (SinticBoliviaSBModuleArgs* args);
void epos_sb_moduleinventory_hook_set_user_data (SinticBoliviaSBModuleArgs* args);
EPosSB_ModuleInventory* epos_sb_moduleinventory_new (void);
EPosSB_ModuleInventory* epos_sb_moduleinventory_construct (GType object_type);
GType sb_get_module_libinventory_type (GModule* inventory_module);
GType epos_eassembly_component_get_type (void) G_GNUC_CONST;
GType epos_eproduct_get_type (void) G_GNUC_CONST;
EPosEAssemblyComponent* epos_eassembly_component_new (void);
EPosEAssemblyComponent* epos_eassembly_component_construct (GType object_type);
EPosEAssemblyComponent* epos_eassembly_component_new_from_id (gint id);
EPosEAssemblyComponent* epos_eassembly_component_construct_from_id (GType object_type, gint id);
EPosEAssemblyComponent* epos_eassembly_component_new_from_assembly_id_and_product_id (gint assembly_id, gint product_id);
EPosEAssemblyComponent* epos_eassembly_component_construct_from_assembly_id_and_product_id (GType object_type, gint assembly_id, gint product_id);
void epos_eassembly_component_GetDbData (EPosEAssemblyComponent* self, gint id);
void epos_eassembly_component_SetDbData (EPosEAssemblyComponent* self, SinticBoliviaDatabaseSBDBRow* data);
gint epos_eassembly_component_get_Id (EPosEAssemblyComponent* self);
gint epos_eassembly_component_get_ProductId (EPosEAssemblyComponent* self);
gint epos_eassembly_component_get_QtyRequired (EPosEAssemblyComponent* self);
gint epos_eassembly_component_get_UOMId (EPosEAssemblyComponent* self);
GType epos_eassembly_get_type (void) G_GNUC_CONST;
EPosEAssembly* epos_eassembly_new (void);
EPosEAssembly* epos_eassembly_construct (GType object_type);
EPosEAssembly* epos_eassembly_new_from_id (gint id);
EPosEAssembly* epos_eassembly_construct_from_id (GType object_type, gint id);
void epos_eassembly_GetDbData (EPosEAssembly* self, gint id);
void epos_eassembly_GetDbComponents (EPosEAssembly* self);
gint epos_eassembly_get_Id (EPosEAssembly* self);
const gchar* epos_eassembly_get_Name (EPosEAssembly* self);
const gchar* epos_eassembly_get_Description (EPosEAssembly* self);
gint epos_eassembly_get_StoreId (EPosEAssembly* self);
GeeArrayList* epos_eassembly_get_Components (EPosEAssembly* self);
GType epos_catalog_get_type (void) G_GNUC_CONST;
EPosCatalog* epos_catalog_new (void);
EPosCatalog* epos_catalog_construct (GType object_type);
void epos_catalog_SetMargins (EPosCatalog* self, gfloat top, gfloat right, gfloat bottom, gfloat left);
void epos_catalog_WriteText (EPosCatalog* self, const gchar* text, const gchar* align, gfloat font_size, const gchar* color);
void epos_catalog_Draw (EPosCatalog* self);
gboolean epos_catalog_CheckNewPage (EPosCatalog* self, gfloat obj_height);
gchar* epos_catalog_Save (EPosCatalog* self, const gchar* name);
void epos_catalog_Preview (EPosCatalog* self, const gchar* name);
void epos_catalog_Print (EPosCatalog* self, const gchar* name, const gchar* printer);
GType epos_order_get_type (void) G_GNUC_CONST;
EPosOrder* epos_order_new (void);
EPosOrder* epos_order_construct (GType object_type);
EPosOrder* epos_order_new_from_id (gint order_id);
EPosOrder* epos_order_construct_from_id (GType object_type, gint order_id);
void epos_order_GetDbData (EPosOrder* self, gint order_id);
void epos_order_SetDbData (EPosOrder* self, SinticBoliviaDatabaseSBDBRow* row);
void epos_order_GetDbItems (EPosOrder* self, gint order_id);
gint epos_order_get_Id (EPosOrder* self);
const gchar* epos_order_get_Code (EPosOrder* self);
gint epos_order_get_StoreId (EPosOrder* self);
gint epos_order_get_SupplierId (EPosOrder* self);
gint epos_order_get_NumItems (EPosOrder* self);
gdouble epos_order_get_SubTotal (EPosOrder* self);
gdouble epos_order_get_TaxTotal (EPosOrder* self);
gdouble epos_order_get_Discount (EPosOrder* self);
gdouble epos_order_get_Total (EPosOrder* self);
const gchar* epos_order_get_Details (EPosOrder* self);
const gchar* epos_order_get_Status (EPosOrder* self);
gint epos_order_get_UserId (EPosOrder* self);
const gchar* epos_order_get_OrderDate (EPosOrder* self);
const gchar* epos_order_get_DeliveryDate (EPosOrder* self);
const gchar* epos_order_get_LastModificationDate (EPosOrder* self);
const gchar* epos_order_get_CreationDate (EPosOrder* self);
GeeArrayList* epos_order_get_Items (EPosOrder* self);
GType epos_pdf_cell_get_type (void) G_GNUC_CONST;
GType epos_pdf_row_get_type (void) G_GNUC_CONST;
EPosPdfCell* epos_pdf_cell_new (void);
EPosPdfCell* epos_pdf_cell_construct (GType object_type);
EPosPdfCell* epos_pdf_cell_new_with_row (EPosPdfRow* row);
EPosPdfCell* epos_pdf_cell_construct_with_row (GType object_type, EPosPdfRow* row);
void epos_pdf_cell_SetText (EPosPdfCell* self, const gchar* text);
void epos_pdf_cell_SetImage (EPosPdfCell* self, HPDF_Image* image);
void epos_pdf_cell_Draw (EPosPdfCell* self);
GeeArrayList* epos_pdf_cell_BuildCellText (EPosPdfCell* self, gfloat font_size, const gchar* text);
void epos_pdf_cell_set_Border (EPosPdfCell* self, gboolean value);
GType epos_pdf_table_get_type (void) G_GNUC_CONST;
EPosPdfRow* epos_pdf_row_new (void);
EPosPdfRow* epos_pdf_row_construct (GType object_type);
EPosPdfRow* epos_pdf_row_new_with_table (EPosPdfTable* table);
EPosPdfRow* epos_pdf_row_construct_with_table (GType object_type, EPosPdfTable* table);
EPosPdfCell* epos_pdf_row_AddCell (EPosPdfRow* self);
void epos_pdf_row_calculateRowSize (EPosPdfRow* self);
void epos_pdf_row_Draw (EPosPdfRow* self);
gint epos_pdf_row_get_Size (EPosPdfRow* self);
EPosPdfTable* epos_pdf_table_new (HPDF_Doc* doc, HPDF_Page* page, HPDF_Font* font, gfloat width, gfloat source_x, gfloat source_y);
EPosPdfTable* epos_pdf_table_construct (GType object_type, HPDF_Doc* doc, HPDF_Page* page, HPDF_Font* font, gfloat width, gfloat source_x, gfloat source_y);
void epos_pdf_table_SetColumnsWidth (EPosPdfTable* self, gfloat* widths, int widths_length1);
void epos_pdf_table_SetTableHeaders (EPosPdfTable* self, gchar** headers, int headers_length1);
EPosPdfRow* epos_pdf_table_AddRow (EPosPdfTable* self);
EPosPdfCell* epos_pdf_table_AddCell (EPosPdfTable* self);
void epos_pdf_table_AddTextCell (EPosPdfTable* self, const gchar* text, const gchar* align, gfloat font_size, gboolean border, gint span, const gchar* bg, const gchar* fg);
void epos_pdf_table_Draw (EPosPdfTable* self);
EPosEProduct* epos_eproduct_new (void);
EPosEProduct* epos_eproduct_construct (GType object_type);
EPosEProduct* epos_eproduct_new_from_id (gint id);
EPosEProduct* epos_eproduct_construct_from_id (GType object_type, gint id);
EPosEProduct* epos_eproduct_new_with_db_data (SinticBoliviaDatabaseSBDBRow* row);
EPosEProduct* epos_eproduct_construct_with_db_data (GType object_type, SinticBoliviaDatabaseSBDBRow* row);
void epos_eproduct_GetDbData (EPosEProduct* self, gint id);
void epos_eproduct_SetDbData (EPosEProduct* self, SinticBoliviaDatabaseSBDBRow* row, gboolean get_cats, gboolean get_images);
void epos_eproduct_getCategories (EPosEProduct* self);
void epos_eproduct_getImages (EPosEProduct* self);
gchar* epos_eproduct_GetThumbnail (EPosEProduct* self);
glong epos_eproduct_AddMeta (gint pid, const gchar* meta_key, GValue* meta_value);
gchar* epos_eproduct_GetMeta (gint pid, const gchar* meta_key);
gboolean epos_eproduct_UpdateMeta (gint pid, const gchar* meta_key, GValue* meta_value);
gint epos_eproduct_get_Id (EPosEProduct* self);
const gchar* epos_eproduct_get_Code (EPosEProduct* self);
const gchar* epos_eproduct_get_InternalCode (EPosEProduct* self);
gint epos_eproduct_get_ExternId (EPosEProduct* self);
const gchar* epos_eproduct_get_Name (EPosEProduct* self);
const gchar* epos_eproduct_get_Description (EPosEProduct* self);
const gchar* epos_eproduct_get_SerialNumber (EPosEProduct* self);
const gchar* epos_eproduct_get_Barcode (EPosEProduct* self);
gdouble epos_eproduct_get_Cost (EPosEProduct* self);
gdouble epos_eproduct_get_Price (EPosEProduct* self);
gdouble epos_eproduct_get_Price2 (EPosEProduct* self);
gint epos_eproduct_get_Quantity (EPosEProduct* self);
gint epos_eproduct_get_MinStock (EPosEProduct* self);
gint epos_eproduct_get_StoreId (EPosEProduct* self);
void epos_eproduct_set_StoreId (EPosEProduct* self, gint value);
gint epos_eproduct_get_AuthorId (EPosEProduct* self);
const gchar* epos_eproduct_get_Status (EPosEProduct* self);
GeeArrayList* epos_eproduct_get_ImageFiles (EPosEProduct* self);
GeeArrayList* epos_eproduct_get_CategoriesIds (EPosEProduct* self);
GeeArrayList* epos_eproduct_get_Categories (EPosEProduct* self);
gint epos_eproduct_get_LineId (EPosEProduct* self);
gint epos_eproduct_get_DepartmentId (EPosEProduct* self);
gint epos_eproduct_get_UnitMeasureId (EPosEProduct* self);
GType epos_epurchase_order_item_get_type (void) G_GNUC_CONST;
EPosEPurchaseOrderItem* epos_epurchase_order_item_new (void);
EPosEPurchaseOrderItem* epos_epurchase_order_item_construct (GType object_type);
EPosEPurchaseOrderItem* epos_epurchase_order_item_new_from_id (gint id);
EPosEPurchaseOrderItem* epos_epurchase_order_item_construct_from_id (GType object_type, gint id);
EPosEPurchaseOrderItem* epos_epurchase_order_item_new_with_db_data (SinticBoliviaDatabaseSBDBRow* data);
EPosEPurchaseOrderItem* epos_epurchase_order_item_construct_with_db_data (GType object_type, SinticBoliviaDatabaseSBDBRow* data);
void epos_epurchase_order_item_GetDbData (EPosEPurchaseOrderItem* self, gint id);
gint epos_epurchase_order_item_get_Id (EPosEPurchaseOrderItem* self);
gint epos_epurchase_order_item_get_ProductId (EPosEPurchaseOrderItem* self);
gint epos_epurchase_order_item_get_OrderId (EPosEPurchaseOrderItem* self);
const gchar* epos_epurchase_order_item_get_Name (EPosEPurchaseOrderItem* self);
gint epos_epurchase_order_item_get_QtyOrdered (EPosEPurchaseOrderItem* self);
gint epos_epurchase_order_item_get_QtyReceived (EPosEPurchaseOrderItem* self);
gdouble epos_epurchase_order_item_get_SupplyPrice (EPosEPurchaseOrderItem* self);
gdouble epos_epurchase_order_item_get_SubTotal (EPosEPurchaseOrderItem* self);
gdouble epos_epurchase_order_item_get_TotalTax (EPosEPurchaseOrderItem* self);
gdouble epos_epurchase_order_item_get_Discount (EPosEPurchaseOrderItem* self);
gdouble epos_epurchase_order_item_get_Total (EPosEPurchaseOrderItem* self);
const gchar* epos_epurchase_order_item_get_Status (EPosEPurchaseOrderItem* self);
GType epos_purchase_order_get_type (void) G_GNUC_CONST;
EPosPurchaseOrder* epos_purchase_order_new (void);
EPosPurchaseOrder* epos_purchase_order_construct (GType object_type);
EPosPurchaseOrder* epos_purchase_order_new_from_id (gint order_id);
EPosPurchaseOrder* epos_purchase_order_construct_from_id (GType object_type, gint order_id);
GType woocommerce_sale_get_type (void) G_GNUC_CONST;
WoocommerceSale* woocommerce_sale_new (void);
WoocommerceSale* woocommerce_sale_construct (GType object_type);
GType epos_esupplier_get_type (void) G_GNUC_CONST;
EPosESupplier* epos_esupplier_new (void);
EPosESupplier* epos_esupplier_construct (GType object_type);
EPosESupplier* epos_esupplier_new_with_db_data (SinticBoliviaDatabaseSBDBRow* db_data);
EPosESupplier* epos_esupplier_construct_with_db_data (GType object_type, SinticBoliviaDatabaseSBDBRow* db_data);
EPosESupplier* epos_esupplier_new_from_id (gint supplier_id);
EPosESupplier* epos_esupplier_construct_from_id (GType object_type, gint supplier_id);
void epos_esupplier_GetDbData (EPosESupplier* self, gint supplier_id);
gint epos_esupplier_get_Id (EPosESupplier* self);
gint epos_esupplier_get_StoreId (EPosESupplier* self);
const gchar* epos_esupplier_get_Name (EPosESupplier* self);
const gchar* epos_esupplier_get_Address (EPosESupplier* self);
const gchar* epos_esupplier_get_Telephone1 (EPosESupplier* self);
const gchar* epos_esupplier_get_Telephone2 (EPosESupplier* self);
const gchar* epos_esupplier_get_Fax (EPosESupplier* self);
const gchar* epos_esupplier_get_City (EPosESupplier* self);
const gchar* epos_esupplier_get_Email (EPosESupplier* self);
const gchar* epos_esupplier_get_ContactPerson (EPosESupplier* self);
const gchar* epos_esupplier_get_Key (EPosESupplier* self);
GType epos_etax_rate_get_type (void) G_GNUC_CONST;
EPosETaxRate* epos_etax_rate_new (void);
EPosETaxRate* epos_etax_rate_construct (GType object_type);
EPosETaxRate* epos_etax_rate_new_from_id (gint id);
EPosETaxRate* epos_etax_rate_construct_from_id (GType object_type, gint id);
gint epos_etax_rate_get_Id (EPosETaxRate* self);
const gchar* epos_etax_rate_get_Name (EPosETaxRate* self);
gdouble epos_etax_rate_get_Rate (EPosETaxRate* self);
GType woocommerce_invoice_ticket_invoice_get_type (void) G_GNUC_CONST;
WoocommerceInvoiceTicketInvoice* woocommerce_invoice_ticket_invoice_new (void);
WoocommerceInvoiceTicketInvoice* woocommerce_invoice_ticket_invoice_construct (GType object_type);
WoocommerceInvoiceTicketInvoice* woocommerce_invoice_ticket_invoice_new_with_context (cairo_t* ctx);
WoocommerceInvoiceTicketInvoice* woocommerce_invoice_ticket_invoice_construct_with_context (GType object_type, cairo_t* ctx);
cairo_t* woocommerce_invoice_ticket_invoice_GetContext (WoocommerceInvoiceTicketInvoice* self);
void woocommerce_invoice_ticket_invoice_SetContext (WoocommerceInvoiceTicketInvoice* self, cairo_t* ctx);
void woocommerce_invoice_ticket_invoice_SetWidth (WoocommerceInvoiceTicketInvoice* self, gint width);
void woocommerce_invoice_ticket_invoice_SetHeight (WoocommerceInvoiceTicketInvoice* self, gint height);
void woocommerce_invoice_ticket_invoice_AddLine (WoocommerceInvoiceTicketInvoice* self, const gchar* text, const gchar* align);
void woocommerce_invoice_ticket_invoice_Draw (WoocommerceInvoiceTicketInvoice* self);
gchar* woocommerce_invoice_ticket_invoice_TextLeft (WoocommerceInvoiceTicketInvoice* self, const gchar* _str);
gchar* woocommerce_invoice_ticket_invoice_TextCenter (WoocommerceInvoiceTicketInvoice* self, const gchar* par1);
gchar* woocommerce_invoice_ticket_invoice_TextRight (WoocommerceInvoiceTicketInvoice* self, const gchar* par1);
gfloat woocommerce_invoice_ticket_invoice_Pixel2Mm (WoocommerceInvoiceTicketInvoice* self, gfloat _pix);
gfloat woocommerce_invoice_ticket_invoice_Mm2Pixel (WoocommerceInvoiceTicketInvoice* self, gfloat _mm);
void woocommerce_invoice_ticket_invoice_buildPageFrame (WoocommerceInvoiceTicketInvoice* self);
GType epos_widget_item_types_get_type (void) G_GNUC_CONST;
EPosWidgetItemTypes* epos_widget_item_types_new (void);
EPosWidgetItemTypes* epos_widget_item_types_construct (GType object_type);
void epos_widget_item_types_Build (EPosWidgetItemTypes* self);
void epos_widget_item_types_SetEvents (EPosWidgetItemTypes* self);
void epos_widget_item_types_Refresh (EPosWidgetItemTypes* self);
void epos_widget_item_types_OnButtonAddClicked (EPosWidgetItemTypes* self);
void epos_widget_item_types_OnButtonEditClicked (EPosWidgetItemTypes* self);
void epos_widget_item_types_OnButtonDeleteClicked (EPosWidgetItemTypes* self);
void epos_widget_item_types_OnButtonCancelClicked (EPosWidgetItemTypes* self);
void epos_widget_item_types_OnButtonSaveClicked (EPosWidgetItemTypes* self);
GType epos_widget_adjustments_get_type (void) G_GNUC_CONST;
GType epos_widget_adjustments_columns_get_type (void) G_GNUC_CONST;
EPosWidgetAdjustments* epos_widget_adjustments_new (void);
EPosWidgetAdjustments* epos_widget_adjustments_construct (GType object_type);
void epos_widget_adjustments_Build (EPosWidgetAdjustments* self);
void epos_widget_adjustments_SetEvents (EPosWidgetAdjustments* self);
void epos_widget_adjustments_OnComboBoxStoreChanged (EPosWidgetAdjustments* self);
void epos_widget_adjustments_OnButtonNewClicked (EPosWidgetAdjustments* self);
void epos_widget_adjustments_OnButtonCancelClicked (EPosWidgetAdjustments* self);
void epos_widget_adjustments_Refresh (EPosWidgetAdjustments* self, gint store_id);
GType epos_widget_assemblies_get_type (void) G_GNUC_CONST;
EPosWidgetAssemblies* epos_widget_assemblies_new (void);
EPosWidgetAssemblies* epos_widget_assemblies_construct (GType object_type);
void epos_widget_assemblies_Build (EPosWidgetAssemblies* self);
void epos_widget_assemblies_SetEvents (EPosWidgetAssemblies* self);
void epos_widget_assemblies_Refresh (EPosWidgetAssemblies* self);
void epos_widget_assemblies_OnButtonAddClicked (EPosWidgetAssemblies* self);
void epos_widget_assemblies_OnButtonEditClicked (EPosWidgetAssemblies* self);
void epos_widget_assemblies_OnButtonDeleteClicked (EPosWidgetAssemblies* self);
GType epos_widget_currencies_get_type (void) G_GNUC_CONST;
EPosWidgetCurrencies* epos_widget_currencies_new (void);
EPosWidgetCurrencies* epos_widget_currencies_construct (GType object_type);
void epos_widget_currencies_Build (EPosWidgetCurrencies* self);
void epos_widget_currencies_SetEvents (EPosWidgetCurrencies* self);
void epos_widget_currencies_Refresh (EPosWidgetCurrencies* self);
void epos_widget_currencies_OnButtonAddClicked (EPosWidgetCurrencies* self);
void epos_widget_currencies_OnButtonEditClicked (EPosWidgetCurrencies* self);
void epos_widget_currencies_OnButtonDeleteClicked (EPosWidgetCurrencies* self);
void epos_widget_currencies_OnButtonSaveClicked (EPosWidgetCurrencies* self);
void epos_widget_currencies_OnButtonCancelClicked (EPosWidgetCurrencies* self);
GType epos_widget_product_departments_get_type (void) G_GNUC_CONST;
EPosWidgetProductDepartments* epos_widget_product_departments_new (void);
EPosWidgetProductDepartments* epos_widget_product_departments_construct (GType object_type);
void epos_widget_product_departments_Build (EPosWidgetProductDepartments* self);
void epos_widget_product_departments_Refresh (EPosWidgetProductDepartments* self);
void epos_widget_product_departments_SetEvents (EPosWidgetProductDepartments* self);
void epos_widget_product_departments_OnButtonNewClicked (EPosWidgetProductDepartments* self);
void epos_widget_product_departments_OnButtonEditClicked (EPosWidgetProductDepartments* self);
void epos_widget_product_departments_OnButtonDeleteClicked (EPosWidgetProductDepartments* self);
void epos_widget_product_departments_OnButtonCancelClicked (EPosWidgetProductDepartments* self);
void epos_widget_product_departments_OnButtonSaveClicked (EPosWidgetProductDepartments* self);
GType epos_widget_inventory_get_type (void) G_GNUC_CONST;
EPosWidgetInventory* epos_widget_inventory_new (void);
EPosWidgetInventory* epos_widget_inventory_construct (GType object_type);
void epos_widget_inventory_SetEvents (EPosWidgetInventory* self);
void epos_widget_inventory_BuildStores (EPosWidgetInventory* self);
void epos_widget_inventory_BuildCategories (EPosWidgetInventory* self);
void epos_widget_inventory_BuildProducts (EPosWidgetInventory* self);
void epos_widget_inventory_RefreshStores (EPosWidgetInventory* self);
void epos_widget_inventory_RefreshCategories (EPosWidgetInventory* self, gint store_id);
void epos_widget_inventory_RefreshProducts (EPosWidgetInventory* self, gint store_id, gint category_id);
void epos_widget_inventory_OnButtonAddStoreClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonEditStoreClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonDeleteStoreClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonSaveStoreClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonCancelStoreClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonNewCategoryClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonEditCategoryClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonDeleteCategoryClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnComboBoxCategoriesStoreChanged (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonSaveCategoryClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonNewProductClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonEditProductClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnComboboxStoreChanged (EPosWidgetInventory* self);
void epos_widget_inventory_OnComboboxCategoryChanged (EPosWidgetInventory* self);
void epos_widget_inventory_OnButtonRefreshProductsClicked (EPosWidgetInventory* self);
void epos_widget_inventory_OnPrintCatalogActivated (EPosWidgetInventory* self);
void epos_widget_inventory_OnPrintLabelsActivated (EPosWidgetInventory* self);
gint epos_widget_inventory_get_productsPage (EPosWidgetInventory* self);
void epos_widget_inventory_set_productsPage (EPosWidgetInventory* self, gint value);
GType epos_window_new_assembly_get_type (void) G_GNUC_CONST;
EPosWindowNewAssembly* epos_window_new_assembly_new (void);
EPosWindowNewAssembly* epos_window_new_assembly_construct (GType object_type);
void epos_window_new_assembly_Build (EPosWindowNewAssembly* self);
void epos_window_new_assembly_FillForm (EPosWindowNewAssembly* self);
void epos_window_new_assembly_SetEvents (EPosWindowNewAssembly* self);
gboolean epos_window_new_assembly_OnEntrySearchProductKeyReleaseEvent (EPosWindowNewAssembly* self, GdkEventKey* event);
gboolean epos_window_new_assembly_OnSearchProductMatchCompletion (EPosWindowNewAssembly* self, GtkTreeModel* model, GtkTreeIter* iter);
void epos_window_new_assembly_OnButtonAddClicked (EPosWindowNewAssembly* self);
void epos_window_new_assembly_AddProduct (EPosWindowNewAssembly* self, gint product_id, gint qty, gint uom_id);
void epos_window_new_assembly_OnButtonCancelClicked (EPosWindowNewAssembly* self);
void epos_window_new_assembly_OnButtonSaveClicked (EPosWindowNewAssembly* self);
void epos_window_new_assembly_SetAssembly (EPosWindowNewAssembly* self, EPosEAssembly* assembly);
gint epos_window_new_assembly_get_StoreId (EPosWindowNewAssembly* self);
void epos_window_new_assembly_set_StoreId (EPosWindowNewAssembly* self, gint value);
GType epos_widget_new_product_get_type (void) G_GNUC_CONST;
EPosWidgetNewProduct* epos_widget_new_product_new (void);
EPosWidgetNewProduct* epos_widget_new_product_construct (GType object_type);
EPosWidgetNewProduct* epos_widget_new_product_new_with_product (EPosEProduct* prod);
EPosWidgetNewProduct* epos_widget_new_product_construct_with_product (GType object_type, EPosEProduct* prod);
void epos_widget_new_product_Build (EPosWidgetNewProduct* self);
void epos_widget_new_product_SetEvents (EPosWidgetNewProduct* self);
void epos_widget_new_product_FillCategories (EPosWidgetNewProduct* self, gint store_id);
void epos_widget_new_product_OnButtonAddImageClicked (EPosWidgetNewProduct* self);
void epos_widget_new_product_addImage (EPosWidgetNewProduct* self, const gchar* filename, gint id);
void epos_widget_new_product_OnButtonCancelClicked (EPosWidgetNewProduct* self);
void epos_widget_new_product_OnButtonSaveClicked (EPosWidgetNewProduct* self);
void epos_widget_new_product_OnButtonAddSnClicked (EPosWidgetNewProduct* self);
void epos_widget_new_product_OnButtonRemoveSnClicked (EPosWidgetNewProduct* self);
gboolean epos_widget_new_product_OnEntrySearchSupplierKeyReleaseEvent (EPosWidgetNewProduct* self, GdkEventKey* event);
gboolean epos_widget_new_product_OnSearchSupplierCompletionMatchSelected (EPosWidgetNewProduct* self, GtkTreeModel* model, GtkTreeIter* iter);
void epos_widget_new_product_OnButtonAddSupplierClicked (EPosWidgetNewProduct* self);
void epos_widget_new_product_AddSupplier (EPosWidgetNewProduct* self, EPosESupplier* supplier);
GType epos_widget_new_supplier_get_type (void) G_GNUC_CONST;
EPosWidgetNewSupplier* epos_widget_new_supplier_new (void);
EPosWidgetNewSupplier* epos_widget_new_supplier_construct (GType object_type);
void epos_widget_new_supplier_Build (EPosWidgetNewSupplier* self);
void epos_widget_new_supplier_FillForm (EPosWidgetNewSupplier* self);
void epos_widget_new_supplier_SetEvents (EPosWidgetNewSupplier* self);
void epos_widget_new_supplier_OnButtonCancelClicked (EPosWidgetNewSupplier* self);
void epos_widget_new_supplier_OnButtonSaveClicked (EPosWidgetNewSupplier* self);
void epos_widget_new_supplier_SetSupplier (EPosWidgetNewSupplier* self, gint supplier_id);
GType epos_widget_product_lines_get_type (void) G_GNUC_CONST;
EPosWidgetProductLines* epos_widget_product_lines_new (void);
EPosWidgetProductLines* epos_widget_product_lines_construct (GType object_type);
void epos_widget_product_lines_Build (EPosWidgetProductLines* self);
void epos_widget_product_lines_SetEvents (EPosWidgetProductLines* self);
void epos_widget_product_lines_Refresh (EPosWidgetProductLines* self);
void epos_widget_product_lines_OnButtonNewClicked (EPosWidgetProductLines* self);
void epos_widget_product_lines_OnButtonEditClicked (EPosWidgetProductLines* self);
void epos_widget_product_lines_OnButtonDeleteClicked (EPosWidgetProductLines* self);
void epos_widget_product_lines_OnButtonCancelClicked (EPosWidgetProductLines* self);
void epos_widget_product_lines_OnButtonSaveClicked (EPosWidgetProductLines* self);
GType epos_widget_products_search_get_type (void) G_GNUC_CONST;
GType epos_widget_products_search_columns_get_type (void) G_GNUC_CONST;
EPosWidgetProductsSearch* epos_widget_products_search_new (void);
EPosWidgetProductsSearch* epos_widget_products_search_construct (GType object_type);
void epos_widget_products_search_Build (EPosWidgetProductsSearch* self);
void epos_widget_products_search_SetEvents (EPosWidgetProductsSearch* self);
void epos_widget_products_search_Refresh (EPosWidgetProductsSearch* self, gint store_id, GeeArrayList* items);
GtkTreeIter* epos_widget_products_search_GetSelected (EPosWidgetProductsSearch* self);
gboolean epos_widget_products_search_OnEntrySearchKeReleaseEvent (EPosWidgetProductsSearch* self, GdkEventKey* e);
GtkListStore* epos_widget_products_search_get_Model (EPosWidgetProductsSearch* self);
GType epos_widget_purchase_order_get_type (void) G_GNUC_CONST;
GType epos_widget_purchase_order_columns_get_type (void) G_GNUC_CONST;
EPosWidgetPurchaseOrder* epos_widget_purchase_order_new (void);
EPosWidgetPurchaseOrder* epos_widget_purchase_order_construct (GType object_type);
void epos_widget_purchase_order_Build (EPosWidgetPurchaseOrder* self);
void epos_widget_purchase_order_SetEvents (EPosWidgetPurchaseOrder* self);
void epos_widget_purchase_order_FillForm (EPosWidgetPurchaseOrder* self);
gboolean epos_widget_purchase_order_OnEntrySearchProductKeyReleaseEvent (EPosWidgetPurchaseOrder* self, GdkEventKey* event);
gboolean epos_widget_purchase_order_OnCompletionMatchSelected (EPosWidgetPurchaseOrder* self, GtkTreeModel* model, GtkTreeIter* iter);
gboolean epos_widget_purchase_order_isProductInOrder (EPosWidgetPurchaseOrder* self, gint product_id, GtkTreeIter* o_iter);
void epos_widget_purchase_order_OnButtonAddProductClicked (EPosWidgetPurchaseOrder* self);
void epos_widget_purchase_order_calculateRowTotal (EPosWidgetPurchaseOrder* self, GtkTreeIter* iter);
void epos_widget_purchase_order_calculateTotals (EPosWidgetPurchaseOrder* self);
gboolean epos_widget_purchase_order_OnTreeViewProductsButtonReleaseEvent (EPosWidgetPurchaseOrder* self, GdkEventButton* args);
void epos_widget_purchase_order_OnButtonSaveClicked (EPosWidgetPurchaseOrder* self);
void epos_widget_purchase_order_OnButtonCancelClicked (EPosWidgetPurchaseOrder* self);
void epos_widget_purchase_order_SetOrder (EPosWidgetPurchaseOrder* self, EPosPurchaseOrder* order);
void epos_widget_purchase_order_OnButtonReceiveClicked (EPosWidgetPurchaseOrder* self);
void epos_widget_purchase_order_set_Title (EPosWidgetPurchaseOrder* self, const gchar* value);
GType epos_widget_purchase_orders_get_type (void) G_GNUC_CONST;
GType epos_widget_purchase_orders_columns_get_type (void) G_GNUC_CONST;
EPosWidgetPurchaseOrders* epos_widget_purchase_orders_new (void);
EPosWidgetPurchaseOrders* epos_widget_purchase_orders_construct (GType object_type);
void epos_widget_purchase_orders_Build (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_FillForm (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_SetEvents (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_OnComboBoxStoresChanged (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_OnComboBoxStatusChanged (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_OnButtonNewClicked (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_OnButtonEditClicked (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_OnButtonReceiveClicked (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_OnButtonCancelClicked (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_OnButtonPreviewClicked (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_RefreshOrders (EPosWidgetPurchaseOrders* self);
void epos_widget_purchase_orders_GetOrders (EPosWidgetPurchaseOrders* self, gint store_id, const gchar* status, gint page, gint limit);
GType epos_widget_receive_purchase_order_get_type (void) G_GNUC_CONST;
EPosWidgetReceivePurchaseOrder* epos_widget_receive_purchase_order_new (EPosPurchaseOrder* order);
EPosWidgetReceivePurchaseOrder* epos_widget_receive_purchase_order_construct (GType object_type, EPosPurchaseOrder* order);
void epos_widget_receive_purchase_order_Build (EPosWidgetReceivePurchaseOrder* self);
void epos_widget_receive_purchase_order_FillOrder (EPosWidgetReceivePurchaseOrder* self);
void epos_widget_receive_purchase_order_SetEvents (EPosWidgetReceivePurchaseOrder* self);
void epos_widget_receive_purchase_order_OnCellQtyReceivedEdited (EPosWidgetReceivePurchaseOrder* self, const gchar* path, const gchar* text);
void epos_widget_receive_purchase_order_OnCellDiscountEdited (EPosWidgetReceivePurchaseOrder* self, const gchar* path, const gchar* text);
void epos_widget_receive_purchase_order_CalculateRowTotal (EPosWidgetReceivePurchaseOrder* self, GtkTreeIter* iter);
void epos_widget_receive_purchase_order_CalculateTotals (EPosWidgetReceivePurchaseOrder* self);
void epos_widget_receive_purchase_order_OnButtonCancelClicked (EPosWidgetReceivePurchaseOrder* self);
void epos_widget_receive_purchase_order_OnButtonReceiveClicked (EPosWidgetReceivePurchaseOrder* self);
GType epos_widget_stock_transfers_get_type (void) G_GNUC_CONST;
EPosWidgetStockTransfers* epos_widget_stock_transfers_new (void);
EPosWidgetStockTransfers* epos_widget_stock_transfers_construct (GType object_type);
void epos_widget_stock_transfers_Build (EPosWidgetStockTransfers* self);
void epos_widget_stock_transfers_SetEvents (EPosWidgetStockTransfers* self);
void epos_widget_stock_transfers_OnButtonRequestClicked (EPosWidgetStockTransfers* self);
void epos_widget_stock_transfers_OnButtonReceiveClicked (EPosWidgetStockTransfers* self);
GType epos_widget_supplier_categories_get_type (void) G_GNUC_CONST;
GType epos_widget_supplier_categories_columns_get_type (void) G_GNUC_CONST;
EPosWidgetSupplierCategories* epos_widget_supplier_categories_new (void);
EPosWidgetSupplierCategories* epos_widget_supplier_categories_construct (GType object_type);
void epos_widget_supplier_categories_Build (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_SetEvents (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_BuildWindow (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_OnButtonNewClicked (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_OnButtonEditClicked (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_OnButtonDeleteClicked (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_OnButtonCancelClicked (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_OnButtonSaveClicked (EPosWidgetSupplierCategories* self);
void epos_widget_supplier_categories_Refresh (EPosWidgetSupplierCategories* self);
GType epos_widget_suppliers_get_type (void) G_GNUC_CONST;
GType epos_widget_suppliers_columns_get_type (void) G_GNUC_CONST;
EPosWidgetSuppliers* epos_widget_suppliers_new (void);
EPosWidgetSuppliers* epos_widget_suppliers_construct (GType object_type);
void epos_widget_suppliers_Build (EPosWidgetSuppliers* self);
void epos_widget_suppliers_FillForm (EPosWidgetSuppliers* self);
void epos_widget_suppliers_SetEvents (EPosWidgetSuppliers* self);
void epos_widget_suppliers_OnButtonNewClicked (EPosWidgetSuppliers* self);
void epos_widget_suppliers_OnButtonEditClicked (EPosWidgetSuppliers* self);
void epos_widget_suppliers_FillSuppliers (EPosWidgetSuppliers* self);
GType epos_widget_transaction_types_get_type (void) G_GNUC_CONST;
EPosWidgetTransactionTypes* epos_widget_transaction_types_new (void);
EPosWidgetTransactionTypes* epos_widget_transaction_types_construct (GType object_type);
void epos_widget_transaction_types_Build (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_BuildDialog (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_SetEvents (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_Refresh (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_OnButtonNewClicked (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_OnButtonEditClicked (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_OnButtonDeleteClicked (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_OnButtonCancelClicked (EPosWidgetTransactionTypes* self);
void epos_widget_transaction_types_OnButtonSaveClicked (EPosWidgetTransactionTypes* self);
GType epos_widget_transactions_get_type (void) G_GNUC_CONST;
GType epos_widget_transactions_columns_get_type (void) G_GNUC_CONST;
EPosWidgetTransactions* epos_widget_transactions_new (void);
EPosWidgetTransactions* epos_widget_transactions_construct (GType object_type);
void epos_widget_transactions_Build (EPosWidgetTransactions* self);
void epos_widget_transactions_SetEvents (EPosWidgetTransactions* self);
void epos_widget_transactions_OnComboBoxStoreChanged (EPosWidgetTransactions* self);
void epos_widget_transactions_OnComboBoxTransactionTypeChanged (EPosWidgetTransactions* self);
void epos_widget_transactions_FillTransactions (EPosWidgetTransactions* self, GeeArrayList* records);
void epos_widget_transactions_OnButtonViewClicked (EPosWidgetTransactions* self);
GType epos_widget_unit_of_measurement_get_type (void) G_GNUC_CONST;
EPosWidgetUnitOfMeasurement* epos_widget_unit_of_measurement_new (void);
EPosWidgetUnitOfMeasurement* epos_widget_unit_of_measurement_construct (GType object_type);
void epos_widget_unit_of_measurement_Build (EPosWidgetUnitOfMeasurement* self);
void epos_widget_unit_of_measurement_SetEvents (EPosWidgetUnitOfMeasurement* self);
void epos_widget_unit_of_measurement_Refresh (EPosWidgetUnitOfMeasurement* self);
void epos_widget_unit_of_measurement_OnButtonNewClicked (EPosWidgetUnitOfMeasurement* self);
void epos_widget_unit_of_measurement_OnButtonEditClicked (EPosWidgetUnitOfMeasurement* self);
void epos_widget_unit_of_measurement_OnButtonDeleteClicked (EPosWidgetUnitOfMeasurement* self);
void epos_widget_unit_of_measurement_OnButtonCancelClicked (EPosWidgetUnitOfMeasurement* self);
void epos_widget_unit_of_measurement_OnButtonSaveClicked (EPosWidgetUnitOfMeasurement* self);
GType epos_widget_view_transaction_get_type (void) G_GNUC_CONST;
GType epos_widget_view_transaction_columns_get_type (void) G_GNUC_CONST;
EPosWidgetViewTransaction* epos_widget_view_transaction_new (void);
EPosWidgetViewTransaction* epos_widget_view_transaction_construct (GType object_type);
void epos_widget_view_transaction_Build (EPosWidgetViewTransaction* self);
void epos_widget_view_transaction_SetEvents (EPosWidgetViewTransaction* self);
void epos_widget_view_transaction_OnButtonPrintClicked (EPosWidgetViewTransaction* self);
void epos_widget_view_transaction_SetTransaction (EPosWidgetViewTransaction* self, GObject* t);
GType epos_dialog_new_adjustment_get_type (void) G_GNUC_CONST;
EPosDialogNewAdjustment* epos_dialog_new_adjustment_new (void);
EPosDialogNewAdjustment* epos_dialog_new_adjustment_construct (GType object_type);
void epos_dialog_new_adjustment_Build (EPosDialogNewAdjustment* self);
void epos_dialog_new_adjustment_SetEvents (EPosDialogNewAdjustment* self);
gboolean epos_dialog_new_adjustment_OnEntrySearchKeReleaseEvent (EPosDialogNewAdjustment* self, GdkEventKey* e);
gboolean epos_dialog_new_adjustment_OnEntrySearchMatchSelected (EPosDialogNewAdjustment* self, GtkTreeModel* model, GtkTreeIter* iter);
void epos_dialog_new_adjustment_OnButtonCancelClicked (EPosDialogNewAdjustment* self);
void epos_dialog_new_adjustment_OnButtonSaveClicked (EPosDialogNewAdjustment* self);
GType epos_inventory_helper_get_type (void) G_GNUC_CONST;
GeeArrayList* epos_inventory_helper_GetStores (void);
GeeArrayList* epos_inventory_helper_GetCategories (gint store_id, guint parent_id);
GeeArrayList* epos_inventory_helper_GetProducts (gint page, gint rows_per_page, glong* total_records);
GeeArrayList* epos_inventory_helper_GetStoreProducts (gint store_id, gint page, gint rows_per_page, glong* total_records, SinticBoliviaDatabaseSBDatabase* _dbh);
GeeArrayList* epos_inventory_helper_GetCategoryProducts (gint cat_id, gint page, gint rows_per_page, glong* total_records);
gboolean epos_inventory_helper_DeleteStore (gint store_id);
GeeArrayList* epos_inventory_helper_GetTransactions (gint store_id, gint type_id, gint page, gint rows_per_page, gint* total_rows);
GeeArrayList* epos_inventory_helper_GetPurchaseOrders (gint store_id, gint page, gint rows_per_page, gint* total_rows);
GeeArrayList* epos_inventory_helper_GetDepartments (void);
GeeArrayList* epos_inventory_helper_GetUnitOfMeasures (void);
GeeHashMap* epos_inventory_helper_GetUnitOfMeasure (gint id);
GeeArrayList* epos_inventory_helper_GetSuppliers (void);
EPosInventoryHelper* epos_inventory_helper_new (void);
EPosInventoryHelper* epos_inventory_helper_construct (GType object_type);


G_END_DECLS

#endif
