/* WoocommerceFees.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __WOOCOMMERCEFEES_H__
#define __WOOCOMMERCEFEES_H__

#include <glib.h>
#include <GtkSinticBolivia.h>
#include <SinticBolivia.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <json-glib/json-glib.h>
#include <gmodule.h>

G_BEGIN_DECLS


#define EPOS_WOOCOMMERCE_TYPE_SB_MODULEWOOCOMMERCEFEES (epos_woocommerce_sb_modulewoocommercefees_get_type ())
#define EPOS_WOOCOMMERCE_SB_MODULEWOOCOMMERCEFEES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_WOOCOMMERCE_TYPE_SB_MODULEWOOCOMMERCEFEES, EPosWoocommerceSB_ModuleWoocommerceFees))
#define EPOS_WOOCOMMERCE_SB_MODULEWOOCOMMERCEFEES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_WOOCOMMERCE_TYPE_SB_MODULEWOOCOMMERCEFEES, EPosWoocommerceSB_ModuleWoocommerceFeesClass))
#define EPOS_WOOCOMMERCE_IS_SB_MODULEWOOCOMMERCEFEES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_WOOCOMMERCE_TYPE_SB_MODULEWOOCOMMERCEFEES))
#define EPOS_WOOCOMMERCE_IS_SB_MODULEWOOCOMMERCEFEES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_WOOCOMMERCE_TYPE_SB_MODULEWOOCOMMERCEFEES))
#define EPOS_WOOCOMMERCE_SB_MODULEWOOCOMMERCEFEES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_WOOCOMMERCE_TYPE_SB_MODULEWOOCOMMERCEFEES, EPosWoocommerceSB_ModuleWoocommerceFeesClass))

typedef struct _EPosWoocommerceSB_ModuleWoocommerceFees EPosWoocommerceSB_ModuleWoocommerceFees;
typedef struct _EPosWoocommerceSB_ModuleWoocommerceFeesClass EPosWoocommerceSB_ModuleWoocommerceFeesClass;
typedef struct _EPosWoocommerceSB_ModuleWoocommerceFeesPrivate EPosWoocommerceSB_ModuleWoocommerceFeesPrivate;

#define EPOS_WOOCOMMERCE_TYPE_WIDGET_ORDER_FEES (epos_woocommerce_widget_order_fees_get_type ())
#define EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPOS_WOOCOMMERCE_TYPE_WIDGET_ORDER_FEES, EPosWoocommerceWidgetOrderFees))
#define EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPOS_WOOCOMMERCE_TYPE_WIDGET_ORDER_FEES, EPosWoocommerceWidgetOrderFeesClass))
#define EPOS_WOOCOMMERCE_IS_WIDGET_ORDER_FEES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPOS_WOOCOMMERCE_TYPE_WIDGET_ORDER_FEES))
#define EPOS_WOOCOMMERCE_IS_WIDGET_ORDER_FEES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EPOS_WOOCOMMERCE_TYPE_WIDGET_ORDER_FEES))
#define EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EPOS_WOOCOMMERCE_TYPE_WIDGET_ORDER_FEES, EPosWoocommerceWidgetOrderFeesClass))

typedef struct _EPosWoocommerceWidgetOrderFees EPosWoocommerceWidgetOrderFees;
typedef struct _EPosWoocommerceWidgetOrderFeesClass EPosWoocommerceWidgetOrderFeesClass;
typedef struct _EPosWoocommerceWidgetOrderFeesPrivate EPosWoocommerceWidgetOrderFeesPrivate;

#define EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_TYPE_COLUMNS (epos_woocommerce_widget_order_fees_columns_get_type ())

struct _EPosWoocommerceSB_ModuleWoocommerceFees {
	SinticBoliviaGtkSBGtkModule parent_instance;
	EPosWoocommerceSB_ModuleWoocommerceFeesPrivate * priv;
	GtkWindow* windowFees;
	EPosWoocommerceWidgetOrderFees* widgetFees;
	GtkLabel* labelTotalFee;
	GtkLabel* labelOrderTotal;
	SinticBoliviaDatabaseSBDatabase* dbh;
};

struct _EPosWoocommerceSB_ModuleWoocommerceFeesClass {
	SinticBoliviaGtkSBGtkModuleClass parent_class;
};

struct _EPosWoocommerceWidgetOrderFees {
	GtkBox parent_instance;
	EPosWoocommerceWidgetOrderFeesPrivate * priv;
	GtkBuilder* ui;
	GtkBox* box1;
	GtkImage* image1;
	GtkButton* buttonClose;
	GtkTreeView* treeviewFees;
	GtkCellRendererCombo* cellComboRates;
	GtkButton* buttonAdd;
	GtkButton* buttonDelete;
	GtkLabel* labelTotal;
	gint items;
};

struct _EPosWoocommerceWidgetOrderFeesClass {
	GtkBoxClass parent_class;
};

typedef enum  {
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_COUNT,
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_TITLE,
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_AMOUNT,
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_TAX,
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_TOTAL,
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_TAX_ID,
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_TAX_RATE,
	EPOS_WOOCOMMERCE_WIDGET_ORDER_FEES_COLUMNS_N_COLS
} EPosWoocommerceWidgetOrderFeesColumns;


GType epos_woocommerce_sb_modulewoocommercefees_get_type (void) G_GNUC_CONST;
GType epos_woocommerce_widget_order_fees_get_type (void) G_GNUC_CONST;
void epos_woocommerce_sb_modulewoocommercefees_AddHooks (EPosWoocommerceSB_ModuleWoocommerceFees* self);
void epos_woocommerce_sb_modulewoocommercefees_hook_before_register_sale (EPosWoocommerceSB_ModuleWoocommerceFees* self, SinticBoliviaSBModuleArgs* args);
void epos_woocommerce_sb_modulewoocommercefees_hook_pos_buttons (EPosWoocommerceSB_ModuleWoocommerceFees* self, SinticBoliviaSBModuleArgs* args);
void epos_woocommerce_sb_modulewoocommercefees_OnButtonAddFeeClicked (EPosWoocommerceSB_ModuleWoocommerceFees* self);
void epos_woocommerce_sb_modulewoocommercefees_hook_pos_totals_grid (EPosWoocommerceSB_ModuleWoocommerceFees* self, SinticBoliviaSBModuleArgs* args);
void epos_woocommerce_sb_modulewoocommercefees_hook_pos_calculate_totals (EPosWoocommerceSB_ModuleWoocommerceFees* self, SinticBoliviaSBModuleArgs* args);
void epos_woocommerce_sb_modulewoocommercefees_hook_wc_before_send_order (EPosWoocommerceSB_ModuleWoocommerceFees* self, SinticBoliviaSBModuleArgs* args);
EPosWoocommerceSB_ModuleWoocommerceFees* epos_woocommerce_sb_modulewoocommercefees_new (void);
EPosWoocommerceSB_ModuleWoocommerceFees* epos_woocommerce_sb_modulewoocommercefees_construct (GType object_type);
GType sb_get_module_libwoocommercefees_type (GModule* mod);
GType epos_woocommerce_widget_order_fees_columns_get_type (void) G_GNUC_CONST;
EPosWoocommerceWidgetOrderFees* epos_woocommerce_widget_order_fees_new (void);
EPosWoocommerceWidgetOrderFees* epos_woocommerce_widget_order_fees_construct (GType object_type);
void epos_woocommerce_widget_order_fees_Build (EPosWoocommerceWidgetOrderFees* self);
void epos_woocommerce_widget_order_fees_SetEvents (EPosWoocommerceWidgetOrderFees* self);
void epos_woocommerce_widget_order_fees_OnTitleEdited (EPosWoocommerceWidgetOrderFees* self, const gchar* path, const gchar* new_text);
void epos_woocommerce_widget_order_fees_OnAmountEdited (EPosWoocommerceWidgetOrderFees* self, const gchar* path, const gchar* new_text);
void epos_woocommerce_widget_order_fees_OnTaxEdited (EPosWoocommerceWidgetOrderFees* self, const gchar* path, const gchar* new_text);
void epos_woocommerce_widget_order_fees_OnTaxChanged (EPosWoocommerceWidgetOrderFees* self, const gchar* path, GtkTreeIter* iter_new);
void epos_woocommerce_widget_order_fees_OnButtonAddClicked (EPosWoocommerceWidgetOrderFees* self);
void epos_woocommerce_widget_order_fees_OnButtonDeleteClicked (EPosWoocommerceWidgetOrderFees* self);
void epos_woocommerce_widget_order_fees_OnButtonCloseClicked (EPosWoocommerceWidgetOrderFees* self);
gchar** epos_woocommerce_widget_order_fees_GetFees (EPosWoocommerceWidgetOrderFees* self, gboolean clear, int* result_length1, int* result_length2);
void epos_woocommerce_widget_order_fees_CalculateRowTotal (EPosWoocommerceWidgetOrderFees* self, GtkTreeIter* iter);
void epos_woocommerce_widget_order_fees_CalculateTotals (EPosWoocommerceWidgetOrderFees* self);
gdouble epos_woocommerce_widget_order_fees_GetTotal (EPosWoocommerceWidgetOrderFees* self);
void epos_woocommerce_widget_order_fees_set_Taxes (EPosWoocommerceWidgetOrderFees* self, GeeArrayList* value);


G_END_DECLS

#endif
